Repository webiny/webiny-js, pull requests merged in 2019-01, with the labels that each got.

#412 Images uploaded locally will be optimized
  packages/demo-api/src/files/create.js
Labels: pkg: webiny-api, tag: bug fix

#430 Handled invalid entity IDs passed via URL
  packages/webiny-admin/src/components/withCrud.js
  packages/webiny-admin/src/components/withCrud/getFormData.js
  packages/webiny-api/src/graphql/crudResolvers.js
  packages/webiny-app-cms/src/admin/views/Pages/Editor.js
  packages/webiny-app-cms/src/admin/views/Pages/PageDetails.js
Labels: pkg: webiny-app-admin, pkg: webiny-app-cms, tag: bug fix

#440 Fix build script for webiny-entity-mongodb.
  packages/webiny-entity-mongodb/package.json
Labels: tag: bug fix

#441 Process root resolver plugins asynchronously.
  packages/demo-api/src/configs/development.js
  packages/demo-api/src/configs/production.js
  packages/webiny-api/src/lambda/lambda.js
Labels: tag: bug fix

#442 Various fixes across the board.
  addons/webiny-integration-cookie-policy/package.json
  packages/demo-theme/package.json
  packages/demo-theme/src/components/Header.js
  packages/webiny-admin/src/components/Views/SimpleForm/SimpleForm.js
  packages/webiny-app-cms/src/admin/plugins/pageDetails/header/revisionSelector/RevisionSelector.js
  packages/webiny-app-cms/src/admin/plugins/pageDetails/previewContent/PagePreview.js
  packages/webiny-app-cms/src/editor/plugins/elements/image/ImageContainer.js
Labels: tag: bug fix

#443 Add displayName to GridInner component.
  packages/webiny-ui/src/Grid/Grid.js
Labels: tag: bug fix

#444 Instead of checking instance types via `instanceof`, `classId` is now used (more reliable)
  packages/webiny-api/src/lambda/lambda.js
  packages/webiny-entity/__tests__/attributes/entityAttribute/general.test.js
  packages/webiny-entity/src/entity.js
  packages/webiny-entity/src/entityAttributes/entitiesAttribute.js
  packages/webiny-entity/src/entityAttributes/entitiesAttributeValue.js
  packages/webiny-entity/src/entityAttributes/entityAttribute.js
  packages/webiny-entity/src/entityAttributes/entityAttributeValue.js
  packages/webiny-entity/src/entityCollection.js
  packages/webiny-entity/src/entityPool.js
Labels: pkg: webiny-entity, tag: bug fix

#449 Move production dependency to "dependencies".
  addons/webiny-integration-cookie-policy/package.json
Labels: tag: bug fix

#450 Add control flags to installation process of Security and CMS.
  packages/webiny-api-cms/.babelrc
  packages/webiny-api-cms/package.json
  packages/webiny-api-cms/src/install/plugins/importData/createDefaultBlocks.js
  packages/webiny-api-cms/src/install/plugins/setupEntities.js
  packages/webiny-api-cms/src/plugins/graphql/menuResolvers/prepareMenuItems.js
  packages/webiny-api-cms/src/plugins/graphql/pageResolvers/listPublishedPages.js
  packages/webiny-api-security/src/entities/User.entity.js
  packages/webiny-api-security/src/install/plugins/importData.js
  packages/webiny-api-security/src/install/plugins/setupEntities.js
  packages/webiny-api-security/src/plugins/graphql/userResolvers/loginUser.js
  packages/webiny-api-security/src/plugins/security.js
  packages/webiny-api/package.json
  packages/webiny-api/src/graphql/InvalidAttributesError.js
  packages/webiny-api/src/graphql/parseBoolean.js
Labels: tag: enhancement

#451 Clean up production dependencies.
  packages/webiny-api-cms/package.json
  packages/webiny-api-security/package.json
  packages/webiny-app/package.json
  packages/webiny-entity-mongodb/package.json
Labels: tag: enhancement

#452 "create" and "update" events will always be executed before main "save" event
  packages/webiny-entity/src/entity.js
Labels: pkg: webiny-entity, tag: new feature

#454 Fixed "listPublishedPages" GraphQL field
  packages/webiny-api-cms/src/plugins/graphql/pageResolvers/listPublishedPages.js
  packages/webiny-entity-mongodb/src/MongoDbDriver.js
Labels: pkg: webiny-api-cms, tag: bug fix
