Repository webiny/webiny-js, pull requests merged in 2020-10, with the labels that each got.

#1272 feat(app-plugin-security-cognito-theme): plugin for to modify login logo
  packages/app-plugin-security-cognito-theme/package.json
  packages/app-plugin-security-cognito-theme/src/admin/types.ts
  packages/app-plugin-security-cognito-theme/src/admin/views/StateContainer.tsx
  packages/app-plugin-security-cognito-theme/tsconfig.build.json
  packages/app-plugin-security-cognito-theme/tsconfig.json
Labels: feature

#1274 feat(app-page-builder): add ability to remove selected icon on button
  packages/app-page-builder/src/editor/components/IconPicker.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/components/IconPicker.tsx
  packages/app-page-builder/src/editor/plugins/elements/button/ButtonContainer.tsx
  packages/app-page-builder/src/editor/plugins/elements/button/ButtonSettings.tsx
  packages/app-page-builder/src/editor/plugins/elements/icon/IconSettings.tsx
Labels: bug, feature

#1292 Page Builder - handle missing object properties and prevent editor from crashing
  packages/app-page-builder/src/editor/plugins/elements/row/RowChild.tsx
Labels: bug

#1280 fix: Allow Relative Paths in Page Builder Links.
  packages/app-page-builder/src/admin/plugins/menuItems/link/LinkForm.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/link/LinkSettings.tsx
  packages/validation/__tests__/url.test.js
  packages/validation/src/validators/url.ts
Labels: hacktoberfest, hacktoberfest-accepted

#1303 fix: Content Model validation message for name field
  packages/app-headless-cms/src/admin/views/ContentModels/NewContentModelDialog.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#1321 feat: show published version of webiny in admin app
  packages/app-admin/src/plugins/Menu/Navigation/index.tsx
  packages/project-utils/bundling/app/index.js
Labels: hacktoberfest, hacktoberfest-accepted
