Repository webiny/webiny-js, pull requests merged in 2020-08, with the labels that each got.

#1134 [Scaffolding] React package
  packages/cli-plugin-scaffold-react-package/CHANGELOG.md
  packages/cli-plugin-scaffold-react-package/index.js
  packages/cli-plugin-scaffold-react-package/package.json
  packages/cli-plugin-scaffold-react-package/template/.babelrc.js
  packages/cli-plugin-scaffold-react-package/template/package.json
  packages/cli-plugin-scaffold-react-package/template/src/index.tsx
  packages/cli-plugin-scaffold-react-package/template/tsconfig.build.json
  packages/cli-plugin-scaffold-react-package/template/tsconfig.json
  packages/cwp-template-cms/template/dependencies.json
  packages/cwp-template-cms/template/webiny.root.js
  packages/cwp-template-full/template/dependencies.json
  packages/cwp-template-full/template/webiny.root.js
  webiny.root.js
Labels: blog, feature

#1171 Feat/1143 cli webiny info
  packages/cli/commands/index.js
  packages/cli/commands/info/index.js
  packages/cwp-template-cms/hooks/api.js
  packages/cwp-template-cms/hooks/apps.js
  packages/cwp-template-full/hooks/api.js
  packages/cwp-template-full/hooks/apps.js
Labels: blog, feature

#1188 Feat: PB dynamic element settings plugin
  packages/app-page-builder/src/editor/plugins/elementSettings/bar/ElementSettingsBar.tsx
  packages/app-page-builder/src/editor/utils.ts
  packages/app-page-builder/src/types.ts
Labels: page-builder

#1192 File Manager - improved file tags form
  packages/app-admin/src/components/FileManager/FileDetails.tsx
  packages/app-admin/src/components/FileManager/FileDetails/Tags.tsx
Labels: feature, improvement

#1199 Fix: headless CMS model description
  package.json
  packages/api-headless-cms/__tests__/manageAPI/snapshots/category.js
  packages/api-headless-cms/__tests__/manageAPI/snapshots/product.js
  packages/api-headless-cms/__tests__/manageAPI/snapshots/review.js
  packages/api-headless-cms/__tests__/readAPI/snapshots/category.js
  packages/api-headless-cms/__tests__/readAPI/snapshots/product.js
  packages/api-headless-cms/__tests__/readAPI/snapshots/review.js
  packages/api-headless-cms/src/content/plugins/schema/createManageSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/createReadSDL.ts
Labels: bug, cms
