Repository webiny/webiny-js, pull requests merged in 2020-06, with the labels that each got.

#908 Introduced the brand new "Files" field
  packages/api-headless-cms/src/content/plugins/graphqlFields/file.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/index.ts
  packages/api-headless-cms/src/content/plugins/modelFields/file.ts
  packages/api-headless-cms/src/content/plugins/modelFields/index.ts
  packages/app-admin/src/components/FileManager.tsx
  packages/app-admin/src/components/FileManager/BottomInfoBar/SupportedFileTypes.tsx
  packages/app-headless-cms/src/admin/components/ContentModelForm/ContentFormRender/RenderFieldElement.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/FileUpload.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/MultipleFile.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/SingleFile.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileField.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileFields.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/index.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/utils.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/index.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/longText/longTextLongTextAreas.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/longText/longTextTextArea.tsx
  packages/app-headless-cms/src/admin/plugins/fields/file.tsx
  packages/app-headless-cms/src/admin/plugins/fields/icons/round_insert_drive_file-24px.svg
  packages/app-headless-cms/src/admin/plugins/fields/index.ts
Labels: feature

#919 Introduced "Predefined Values" functionality
  packages/api-headless-cms/__tests__/mocks/predefinedValues.js
  packages/api-headless-cms/__tests__/mocks/schemaRebuilding.js
  packages/api-headless-cms/__tests__/predefinedValues.test.js
  packages/api-headless-cms/__tests__/schemaRebuilding.test.js
  packages/api-headless-cms/__tests__/utils/useContentHandler/graphql.js
  packages/api-headless-cms/src/content/apolloHandler/createApolloHandler.ts
  packages/api-headless-cms/src/content/plugins/graphql.ts
  packages/api-headless-cms/src/content/plugins/index.ts
  packages/api-headless-cms/src/content/plugins/models/ContentModel/createFieldsModel.ts
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Context/graphql.ts
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog.tsx
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/AppearanceTab.tsx
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/GeneralTab.tsx
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/LocaleSelector.tsx
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/PredefinedValuesTab.tsx
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/PredefinedValuesTab/PredefinedValues.tsx
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/PredefinedValuesTab/functions/getValue.ts
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/EditTab/EditFieldDialog/PredefinedValuesTab/functions/setValue.ts
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/PreviewTab/PreviewTab.tsx
  packages/app-headless-cms/src/admin/components/ContentModelForm/ContentFormRender/RenderFieldElement.tsx
  packages/app-headless-cms/src/admin/components/ContentModelForm/index.tsx
  packages/app-headless-cms/src/admin/plugins/contentDetails/header/localeSelector/LocaleSelector.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/DynamicListMultipleValues.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/checkboxes.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/index.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/radioButtons.tsx
  packages/app-headless-cms/src/admin/plugins/fields/PredefinedValuesDynamicFieldset.tsx
  packages/app-headless-cms/src/admin/plugins/fields/dateTime.tsx
  packages/app-headless-cms/src/admin/plugins/fields/longText.tsx
  packages/app-headless-cms/src/admin/plugins/fields/number.tsx
  packages/app-headless-cms/src/admin/plugins/fields/richText.tsx
  packages/app-headless-cms/src/admin/plugins/fields/text.tsx
  packages/app-headless-cms/src/types.ts
  packages/app-i18n/src/types.ts
  packages/ui/src/DynamicFieldset/Fieldset.tsx
Labels: feature

#1048 Corrected plugin type
  packages/handler-ssr/src/cdnSsrCacheInvalidation.ts
Labels: bug

#1024 Headless CMS - Environment aliases are now automatically transformed to lowercase
  packages/api-headless-cms/__tests__/environmentAliases.test.js
  packages/api-headless-cms/src/content/plugins/models/contentModelGroup.model.ts
  packages/api-headless-cms/src/plugins/models/environmentAlias.model.ts
  packages/api-headless-cms/src/utils/toSlug.ts
  packages/app-headless-cms/src/admin/components/NameSlug.tsx
Labels: bug

#1081 The concurrency limit for the DB Proxy lambda function increased from 15 to 50
  packages/cwp-template-cms/template/api/resources.js
  packages/cwp-template-full/template/api/resources.js
  packages/cwp-template-full/template/apps/resources.js
  sample-project/api/resources.js
Labels: blog, bug

#1085 fix: make sure newly added ref fields cannot reference a model with n…
  packages/api-headless-cms/__tests__/mocks/fields/refInvalidReferences.js
  packages/api-headless-cms/__tests__/refFieldInvalidReferences.test.js
  packages/api-headless-cms/src/content/plugins/modelFields/ref.ts
Labels: bug
