Repository webiny/webiny-js, pull requests merged in 2020-03, with the labels that each got.

#734 fix: tags search & "Pages List" menu item site rendering
  cypress/integration/admin/pageBuilder/menus/pagesListMenuItemType.spec.js
  packages/api-page-builder/src/plugins/graphql/Page.ts
  packages/api-page-builder/src/plugins/graphql/menuResolvers/prepareMenuItems.ts
  packages/app-admin/src/components/SimpleForm/SimpleForm.tsx
  packages/app-page-builder-theme/src/components/DesktopHeader.tsx
  packages/app-page-builder-theme/src/components/Header.tsx
  packages/app-page-builder-theme/src/components/MobileHeader.tsx
  packages/app-page-builder/src/admin/views/Menus/MenusForm.tsx
  packages/app-page-builder/src/admin/views/Menus/MenusForm/MenuItems/MenuItemRenderer.tsx
Labels: bug

#743 feat: improved scopes selection auto-complete component
  cypress.json
  cypress/integration/admin/security/roles/createGroup.spec.js
  cypress/integration/admin/security/roles/createRole.spec.js
  packages/api-form-builder/src/plugins/graphql.ts
  packages/api-page-builder/src/plugins/graphql.ts
  packages/api-security/src/plugins/graphql.ts
  packages/api-security/src/scopes.ts
  packages/app-form-builder/src/admin/plugins/index.ts
  packages/app-form-builder/src/admin/plugins/scopesList.ts
  packages/app-i18n/src/admin/plugins/index.ts
  packages/app-i18n/src/admin/plugins/scopesList.ts
  packages/app-page-builder/src/admin/plugins/index.ts
  packages/app-page-builder/src/admin/plugins/scopesList.ts
  packages/app-security/src/admin/components/ScopesMultiAutoComplete.tsx
  packages/app-security/src/admin/components/index.ts
  packages/app-security/src/admin/plugins/index.ts
  packages/app-security/src/admin/plugins/scopesList.ts
  packages/app-security/src/admin/views/Groups/Groups.tsx
  packages/app-security/src/admin/views/Groups/GroupsDataList.tsx
  packages/app-security/src/admin/views/Roles/Roles.tsx
  packages/app-security/src/admin/views/Roles/RolesDataList.tsx
  packages/app-security/src/admin/views/Roles/RolesForm.tsx
  packages/app-security/src/admin/views/Roles/graphql.ts
  packages/app-security/src/types.ts
  packages/ui/src/AutoComplete/MultiAutoComplete.tsx
Labels: improvement

#746 CDN cache is now invalidated properly upon updating Page Builder settings
  cypress/integration/admin/pageBuilder/menus/pagesListMenuItemType.spec.js
  cypress/integration/admin/settings/siteRefresh.spec.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/support/visitAndReloadOnceInvalidated/index.js
  packages/api-page-builder/src/plugins/useSsrCacheTags.ts
  packages/app-page-builder-theme/src/components/Footer.tsx
  packages/app-page-builder/src/site/components/Page/Page.tsx
Labels: bug

#744 Page Builder - fixed link preloading error
  packages/app-page-builder/src/site/plugins/linkPreload.ts
Labels: bug

#750 I18N Service Plugins - Improved error messaging
  packages/api-i18n/src/plugins/service.ts
Labels: improvement

#777 Improved descriptions for "route", "menu", and "header-*" plugins
  packages/app-admin/src/types.ts
  packages/app/src/types.ts
Labels: feature
