Repository webiny/webiny-js, pull requests merged in 2020-07, with the labels that each got.

#1102 Check if bucket still exists before attempting to remove S3 object
  packages/serverless-aws-s3-object/serverless.js
Labels: blog

#1103 Generate JWT_SECRET, S3_BUCKET, and MONGODB_NAME for all environments
  packages/cwp-template-cms/index.js
  packages/cwp-template-cms/template/api/example.env.json
  packages/cwp-template-cms/template/example.env.json
  packages/cwp-template-full/index.js
  packages/cwp-template-full/template/api/example.env.json
  packages/cwp-template-full/template/example.env.json
Labels: blog

#1095 Fix/environment incorrect url
  packages/api-headless-cms/__tests__/environmentUrl.test.js
  packages/api-headless-cms/src/content/plugins/models.ts
Labels: bug

#1118 Update styles for mobile view
  packages/app-plugin-admin-welcome-screen/src/components/Welcome.tsx
Labels: improvement

#1146 Fix: error when clicking add index with nothing selected
  packages/app-headless-cms/src/admin/components/ContentModelEditor/Tabs/IndexesTab/NewIndexDialog.tsx
Labels: bug, cms

#1159 fix: prepend empty object when doing merge.recursive
  jest.config.base.js
  packages/cwp-template-cms/template/jest.config.base.js
  packages/cwp-template-full/template/jest.config.base.js
Labels: blog, bug

#1148 Fix/api info improvements
  packages/app-admin/src/assets/icons/info.svg
  packages/app-admin/src/plugins/Menu/gqlApiInformation.tsx
  packages/app-headless-cms/src/admin/icons/info.svg
  packages/app-headless-cms/src/admin/views/EnvironmentAliases/EnvironmentAliasesDataList.tsx
  packages/app-headless-cms/src/admin/views/EnvironmentAliases/environmentAliasesUtils.ts
  packages/app-headless-cms/src/admin/views/Environments/EnvironmentsDataList.tsx
Labels: bug

#1145 Fix: contributing doc
  docs/CONTRIBUTING.md
Labels: docs
