Repository webiny/webiny-js, pull requests merged in 2021-12, with the labels that each got.

#2070 fix(api-headless-cms): system version check
  packages/api-headless-cms/src/content/plugins/utils/renderSortEnum.ts
  packages/api-headless-cms/src/plugins/crud/system.crud.ts
Labels: bug

#2081 fix(app-headless-cms): date time with timezone validation
  packages/app-headless-cms/src/admin/plugins/transformers/dateTransformer.ts
Labels: bug

#2082 feat(app-headless-cms): add url to reference entries
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/ref/components/ContentEntriesAutocomplete.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/ref/components/createEntryUrl.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/ref/components/renderItem.tsx
Labels: feature

#2090 fix(api-headless-cms): multiple values in ref field when searching
  packages/api-headless-cms-ddb/src/operations/entry/utils.ts
  packages/api-headless-cms/__tests__/contentAPI/references.test.ts
  packages/db-dynamodb/src/plugins/filters/eq.ts
Labels: bug

#2093 fix(api-headless-cms): references validation
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.read.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry/referenceFieldsMapping.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts
Labels: bug

#2095 fix(api-headless-cms): data loader fetch records
  packages/api-headless-cms-ddb-es/src/operations/entry/dataLoaders.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearchFields.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/fields.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
  packages/api-headless-cms-ddb/src/operations/entry/dataLoaders.ts
  packages/api-headless-cms-ddb/src/operations/entry/index.ts
  packages/api-headless-cms-ddb/src/operations/entry/systemFields.ts
  packages/api-headless-cms/__tests__/storageOperations/entries.test.ts
  packages/api-headless-cms/__tests__/storageOperations/helpers.ts
  packages/api-headless-cms/src/types.ts
  packages/db-dynamodb/src/utils/batchRead.ts
Labels: bug

#2098 fix(api-headless-cms): schema break when no fields in nested obj
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/object.ts
  packages/api-headless-cms/src/content/plugins/schema/createFieldResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/createPreviewResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createReadResolvers.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#2100 feat(api-headless-cms): republish existing entries
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
  packages/api-headless-cms-ddb/src/operations/entry/index.ts
  packages/api-headless-cms/__tests__/contentAPI/republish.entries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/__tests__/utils/useCategoryManageHandler.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveRepublish.ts
  packages/api-headless-cms/src/plugins/crud/system.crud.ts
  packages/api-headless-cms/src/types.ts
  packages/api-upgrade/src/index.ts
  packages/app-headless-cms/package.json
  packages/app-headless-cms/src/admin/plugins/install.tsx
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/UpgradeItemsInfo.tsx
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/createCmsApolloClient.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/createListEntriesQuery.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/createListModelsQuery.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/createRepublishMutation.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/createUpgradeMutation.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/fetchModelEntries.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/5.19.0/types.ts
  packages/app-headless-cms/src/admin/plugins/upgrades/v5.19.0.tsx
  yarn.lock
Labels: feature

#2104 fix(api-headless-cms): republishing entries
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms/__tests__/contentAPI/republish.entries.test.ts
  packages/api-headless-cms/__tests__/utils/tenancySecurity.ts
  packages/api-headless-cms/__tests__/utils/useProductManageHandler.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry/referenceFieldsMapping.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/beforeDelete.ts
Labels: bug

#2109 feat(api-headless-cms): take locale from cms context
  packages/api-headless-cms-ddb-es/src/operations/model/index.ts
  packages/api-headless-cms-ddb/src/operations/entry/keys.ts
  packages/api-headless-cms-ddb/src/operations/model/index.ts
  packages/api-headless-cms/src/content/plugins/crud/index.ts
  packages/api-headless-cms/src/plugins/context.ts
  packages/api-headless-cms/src/plugins/crud/index.ts
Labels: bug

#2110 refactor(api-i18n): split graphq context
  packages/api-file-manager/src/plugins/crud/files.crud.ts
  packages/api-file-manager/src/plugins/graphql.ts
  packages/api-form-builder-so-ddb-es/src/upgrades/5.16.0/index.ts
  packages/api-form-builder/src/plugins/crud/index.ts
  packages/api-form-builder/src/plugins/graphql.ts
  packages/api-i18n-content/src/plugins/index.ts
  packages/api-i18n-content/src/types.ts
  packages/api-i18n/__tests__/locale.lifecycle.test.ts
  packages/api-i18n/__tests__/mocks/lifecycleEvents.ts
  packages/api-i18n/__tests__/mocks/localePlugin.ts
  packages/api-i18n/package.json
  packages/api-i18n/src/graphql/context.ts
  packages/api-i18n/src/graphql/crud/index.ts
  packages/api-i18n/src/graphql/crud/locales.crud.ts
  packages/api-i18n/src/graphql/crud/locales/lifecycleEvent.ts
  packages/api-i18n/src/graphql/crud/system.crud.ts
  packages/api-i18n/src/graphql/graphql.ts
  packages/api-i18n/src/graphql/graphql/base.ts
  packages/api-i18n/src/graphql/graphql/installation.ts
  packages/api-i18n/src/graphql/graphql/locales.ts
  packages/api-i18n/src/graphql/index.ts
  packages/api-i18n/src/graphql/localeContexts.ts
  packages/api-i18n/src/graphql/service.ts
  packages/api-i18n/src/graphql/testing/locales.ts
  packages/api-i18n/src/plugins/I18NLocaleContextPlugin.ts
  packages/api-i18n/src/plugins/LocalePlugin.ts
  packages/api-i18n/src/types.ts
  packages/api-i18n/tsconfig.build.json
  packages/api-i18n/tsconfig.json
  packages/api-page-builder-import-export/__tests__/pageImportExportTask/useHandler.ts
  packages/api-page-builder-import-export/src/graphql/crud/pageImportExportTasks.crud.ts
  packages/api-page-builder-so-ddb-es/src/operations/pages/PageStorageOperations.ts
  packages/api-page-builder-so-ddb-es/src/operations/settings/SettingsStorageOperations.ts
  packages/api-page-builder-so-ddb/src/operations/pages/PageStorageOperations.ts
  packages/api-page-builder-so-ddb/src/operations/settings/SettingsStorageOperations.ts
  packages/api-page-builder/src/graphql/crud/categories.crud.ts
  packages/api-page-builder/src/graphql/crud/menus.crud.ts
  packages/api-page-builder/src/graphql/crud/pageElements.crud.ts
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/crud/settings.crud.ts
  packages/api-page-builder/src/prerendering/prerenderingHandlers.ts
  packages/cli-plugin-scaffold-graphql-service/template/resolvers/TargetDataModelsResolver.ts
  yarn.lock
Labels: feature

#2113 fix(api-file-manager): list tags when no tags defined
  packages/api-file-manager-ddb/src/operations/files/FilesStorageOperations.ts
  packages/api-file-manager/__tests__/files.test.ts
  packages/api-file-manager/src/plugins/crud/files.crud.ts
Labels: bug

#2115 fix(api-i18n-ddb): missing locale plugin
  packages/api-i18n-ddb/__tests__/crud/locales.crud.test.ts
  packages/api-i18n-ddb/__tests__/mocks/originField.ts
  packages/api-i18n-ddb/__tests__/useGqlHandler.ts
Labels: bug

#2114 fix(api-file-manager): tags listing error
  packages/api-file-manager-ddb/src/operations/files/FilesStorageOperations.ts
  packages/api-file-manager/__tests__/files.test.ts
  packages/api-file-manager/src/plugins/crud/files.crud.ts
Labels: bug

#2117 refactor(api-headless-cms): make listEntries internal use method
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/content/plugins/modelManager/DefaultCmsModelManager.ts
  packages/api-headless-cms/src/content/plugins/schema/contentEntries.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#2119 fix: system tenant
  packages/api-file-manager-ddb-es/src/definitions/systemEntity.ts
  packages/api-file-manager-ddb/src/definitions/systemEntity.ts
  packages/api-file-manager/src/plugins/crud/system.crud.ts
  packages/api-file-manager/src/types.ts
  packages/api-i18n-ddb/src/definitions/systemEntity.ts
  packages/api-i18n/src/graphql/crud/system.crud.ts
  packages/api-i18n/src/types.ts
  packages/api-page-builder-so-ddb-es/src/definitions/systemEntity.ts
  packages/api-page-builder-so-ddb/src/definitions/systemEntity.ts
  packages/api-page-builder/src/graphql/crud/system.crud.ts
  packages/api-page-builder/src/types.ts
Labels: bug, feature

#2120 fix(api-headless-cms): empty nested object as first field
  packages/api-headless-cms/__tests__/contentAPI/model.nestedField.test.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/object.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/createPreviewResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createReadResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/createReadSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/schemaPlugins.ts
  packages/api-headless-cms/src/content/plugins/utils/renderFields.ts
  packages/api-headless-cms/src/types.ts
  packages/app-headless-cms/src/admin/views/contentModels/NewContentModelDialog.tsx
Labels: bug

#2125 fix(api-headless-cms-ddb-es): ref field id and entryId exact matches
  packages/api-headless-cms-ddb-es/src/elasticsearch/search/refSearch.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchQueryBuilderValueSearchPlugin.ts
  packages/api-headless-cms/__tests__/contentAPI/references.test.ts
Labels: bug

#2126 fix(app-headless-cms): date field value is sent as null if not changed
  packages/app-headless-cms/src/admin/plugins/transformers/dateTransformer.ts
  packages/app-headless-cms/src/admin/views/contentEntries/ContentEntry/prepareFormData.ts
Labels: bug

#2127 fix(app-headless-cms): title field when in object field
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
Labels: bug

#2129 feat(api-headless-cms): clone model
  packages/api-headless-cms/__tests__/contentAPI/contentModel.clone.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/utils/graphql/contentModel.ts
  packages/api-headless-cms/__tests__/utils/useGqlHandler.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/beforeCreate.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModels.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#2131 feat(app-headless-cms): clone content model
  packages/api-headless-cms/__tests__/contentAPI/contentModel.clone.test.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModels.ts
  packages/api-headless-cms/src/types.ts
  packages/app-headless-cms/src/admin/icons/clone.svg
  packages/app-headless-cms/src/admin/views/contentModels/CloneContentModelDialog.tsx
  packages/app-headless-cms/src/admin/views/contentModels/ContentModels.tsx
  packages/app-headless-cms/src/admin/views/contentModels/ContentModelsDataList.tsx
  packages/app-headless-cms/src/admin/viewsGraphql.ts
Labels: feature

#2123 Fixed React Component Scaffold's `webiny.config.ts` File
  packages/cli-plugin-scaffold-react-component/template/webiny.config.ts
Labels: bug

#2124 `webiny watch` - Fixed `remoteRuntimeLogs` Flag
  packages/cli-plugin-deploy-pulumi/commands/index.js
  packages/cli-plugin-deploy-pulumi/commands/watch.js
Labels: bug

#2132 feat(api-headless-cms): clone model into another locale
  packages/api-headless-cms/__tests__/contentAPI/contentModel.clone.test.ts
  packages/api-headless-cms/__tests__/utils/helpers.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/models.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModels.ts
  packages/api-headless-cms/src/types.ts
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
  packages/app-headless-cms/src/admin/hooks/index.ts
  packages/app-headless-cms/src/admin/hooks/useQueryLocale.ts
  packages/app-headless-cms/src/admin/views/contentModels/CloneContentModelDialog.tsx
Labels: feature

#2133 fix(api-headless-cms-ddb-es): failed listing when missing index
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
Labels: bug

#2136 feat(api-page-builder): add pub/sub methods
  packages/api-dynamic-pages/src/index.ts
  packages/api-dynamic-pages/src/loadDynamicPage.ts
  packages/api-page-builder-import-export/src/exportPages/process/index.ts
  packages/api-page-builder-import-export/src/graphql/crud/pages.crud.ts
  packages/api-page-builder-import-export/src/importPages/process/index.ts
  packages/api-page-builder-so-ddb-es/src/operations/system/InstallationDdbEsPlugin.ts
  packages/api-page-builder-so-ddb-es/src/upgrades/v5.15.0/category.ts
  packages/api-page-builder-so-ddb-es/src/upgrades/v5.15.0/menu.ts
  packages/api-page-builder-so-ddb-es/src/upgrades/v5.15.0/pageElement.ts
  packages/api-page-builder/src/graphql/crud.ts
  packages/api-page-builder/src/graphql/crud/categories.crud.ts
  packages/api-page-builder/src/graphql/crud/menus.crud.ts
  packages/api-page-builder/src/graphql/crud/menus/prepareMenuItems.ts
  packages/api-page-builder/src/graphql/crud/pageElements.crud.ts
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/crud/pages.validation.ts
  packages/api-page-builder/src/graphql/crud/settings.crud.ts
  packages/api-page-builder/src/graphql/crud/system.crud.ts
  packages/api-page-builder/src/graphql/crud/utils/executeCallbacks.ts
  packages/api-page-builder/src/graphql/graphql.ts
  packages/api-page-builder/src/graphql/graphql/base.gql.ts
  packages/api-page-builder/src/graphql/graphql/categories.gql.ts
  packages/api-page-builder/src/graphql/graphql/install.gql.ts
  packages/api-page-builder/src/graphql/graphql/menus.gql.ts
  packages/api-page-builder/src/graphql/graphql/pageElements.gql.ts
  packages/api-page-builder/src/graphql/graphql/pages.gql.ts
  packages/api-page-builder/src/graphql/graphql/pages/pageSettings/general.ts
  packages/api-page-builder/src/graphql/graphql/pages/pageSettings/index.ts
  packages/api-page-builder/src/graphql/graphql/pages/pageSettings/seo.ts
  packages/api-page-builder/src/graphql/graphql/pages/pageSettings/social.ts
  packages/api-page-builder/src/graphql/graphql/settings.gql.ts
  packages/api-page-builder/src/graphql/index.ts
  packages/api-page-builder/src/graphql/types.ts
  packages/api-page-builder/src/plugins/InstallationPlugin.ts
  packages/api-page-builder/src/plugins/MenuPlugin.ts
  packages/api-page-builder/src/plugins/PagePlugin.ts
  packages/api-page-builder/src/plugins/SettingsPlugin.ts
  packages/api-page-builder/src/prerendering/hooks/afterMenuUpdate.ts
  packages/api-page-builder/src/prerendering/hooks/afterPageDelete.ts
  packages/api-page-builder/src/prerendering/hooks/afterPagePublish.ts
  packages/api-page-builder/src/prerendering/hooks/afterPageUnpublish.ts
  packages/api-page-builder/src/prerendering/hooks/afterSettingsUpdate.ts
  packages/api-page-builder/src/prerendering/hooks/index.ts
  packages/api-page-builder/src/prerendering/prerenderingHandlers.ts
Labels: feature

#2144 feat(api-headless-cms): make graphql fields required if field has required validator
  packages/api-headless-cms/__tests__/contentAPI/fieldValidations.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/boolean.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/datetime.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/file.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/longText.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/number.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/object.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/requiredField.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/richText.ts
  packages/api-headless-cms/src/content/plugins/graphqlFields/text.ts
  packages/api-headless-cms/src/content/plugins/storage/object.ts
Labels: feature

#2143 feat: add possibility to output api version in headers
  packages/api-headless-cms/src/content/graphQLHandlerFactory.ts
  packages/handler-graphql/__tests__/graphql.test.ts
  packages/handler-graphql/package.json
  packages/handler-graphql/src/createGraphQLHandler.ts
  packages/handler-graphql/tsconfig.build.json
  packages/handler-graphql/tsconfig.json
  packages/handler-http/package.json
  packages/handler-http/src/index.ts
  packages/handler-http/tsconfig.build.json
  packages/handler-http/tsconfig.json
  packages/project-utils/bundling/function/createBuildConfig.js
  packages/project-utils/bundling/function/createWatchConfig.js
  packages/utils/__tests__/headers.test.ts
  packages/utils/src/headers.ts
  packages/utils/src/index.ts
  yarn.lock
Labels: feature

#2162 refactor(api-page-builder): types
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/crud/pages/compression.ts
  packages/api-page-builder/src/graphql/crud/pages/contentCompression.ts
  packages/api-page-builder/src/graphql/crud/system.crud.ts
  packages/api-page-builder/src/graphql/types.ts
  packages/api-page-builder/src/plugins/JsonpackContentCompressionPlugin.ts
  packages/api-page-builder/src/types.ts
Labels: improvement

#2160 fix: protect installers from unauthorized run
  packages/api-file-manager/src/plugins/crud/system.crud.ts
  packages/api-form-builder/src/plugins/crud/system.crud.ts
  packages/api-i18n/src/graphql/crud/system.crud.ts
  packages/api-page-builder/src/graphql/crud/system.crud.ts
Labels: bug
