Repository webiny/webiny-js, pull requests merged in 2021-03, with the labels that each got.

#1504 fix(api-headless-cms): schema regeneration last changed date
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/predefinedValues.test.ts
  packages/api-headless-cms/__tests__/utils/useBugManageHandler.ts
  packages/api-headless-cms/src/content/graphQLHandlerFactory.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/afterCreate.hook.ts
  packages/api-headless-cms/src/plugins/crud/settings.crud.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#1502 feat: update pb element plugin factory
  apps/admin/code/src/plugins/pageBuilder/editorPlugins.ts
  packages/app-admin/src/components/FileManager/File.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/text/TextSettings.tsx
  packages/app-page-builder/src/editor/plugins/elements/block/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/button/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/cell/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/grid/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/heading/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/icon/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/image/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/imagesList/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/list/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/media/soundcloud/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/media/vimeo/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/media/youtube/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/pagesList/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/paragraph/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/quote/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/social/pinterest/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/social/twitter/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/utils/oembed/createEmbedPlugin.tsx
  packages/app-page-builder/src/render/plugins/elements/button/index.tsx
  packages/app-page-builder/src/render/plugins/elements/embeds/pinterest/index.tsx
  packages/app-page-builder/src/render/plugins/elements/embeds/soundcloud/index.tsx
  packages/app-page-builder/src/render/plugins/elements/embeds/twitter/index.tsx
  packages/app-page-builder/src/render/plugins/elements/embeds/vimeo/index.tsx
  packages/app-page-builder/src/render/plugins/elements/embeds/youtube/index.tsx
  packages/app-page-builder/src/render/plugins/elements/heading/index.tsx
  packages/app-page-builder/src/render/plugins/elements/icon/index.tsx
  packages/app-page-builder/src/render/plugins/elements/image/index.tsx
  packages/app-page-builder/src/render/plugins/elements/imagesList/index.tsx
  packages/app-page-builder/src/render/plugins/elements/list/index.tsx
  packages/app-page-builder/src/render/plugins/elements/pagesList/index.tsx
  packages/app-page-builder/src/render/plugins/elements/paragraph/index.tsx
  packages/app-page-builder/src/render/plugins/elements/quote/index.tsx
  packages/app-page-builder/src/types.ts
Labels: feature

#1503 fix: deny public access to ES domain
  api/pulumi/dev/elasticSearch.ts
  api/pulumi/prod/elasticSearch.ts
  packages/cwp-template-aws/template/api/pulumi/dev/elasticSearch.ts
  packages/cwp-template-aws/template/api/pulumi/prod/elasticSearch.ts
Labels: improvement

#1516 test(api-headless-cms): product sort by price
  packages/api-headless-cms/__tests__/contentAPI/resolvers.read.test.ts
Labels: feature

#1511 fix: add missing permission check
  packages/api-file-manager-s3/package.json
  packages/api-file-manager-s3/src/plugins/graphqlFileStorageS3.ts
  packages/api-file-manager-s3/tsconfig.build.json
  packages/api-file-manager-s3/tsconfig.json
  packages/app-page-builder/src/admin/plugins/pageDetails/header/editRevision/EditRevision.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/pageRevisions/useRevisionHandlers.ts
  packages/app-page-builder/src/admin/plugins/settings/components/websiteSettings/WebsiteSettings.tsx
  packages/app-page-builder/src/admin/views/Pages/Pages.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/Revisions.tsx
  yarn.lock
Labels: bug

#1532 Headless CMS - Search Input Fixes
  packages/app-headless-cms/src/admin/views/ContentEntries/ContentDataList.tsx
Labels: bug

#1513 fix: store and reuse settings to/from a per tenant cache
  packages/api-file-manager/src/plugins/FileStorage.ts
  packages/api-file-manager/src/plugins/context.ts
  packages/api-file-manager/src/plugins/upgrades/v5.0.0/index.ts
  packages/api-form-builder/src/plugins/upgrades/v5.0.0/index.ts
  packages/api-headless-cms/src/plugins/upgrades/v5.0.0/index.ts
  packages/api-page-builder/src/graphql/upgrades/v5.0.0/index.ts
Labels: improvement

#1533 fix(cli-plugin-scaffold-graphql-service): graphql types naming
  packages/cli-plugin-scaffold-admin-app-module/src/index.ts
  packages/cli-plugin-scaffold-graphql-service/src/index.ts
  packages/cli-plugin-scaffold-graphql-service/template/src/graphql.ts
Labels: bug

#1530 feat(cli-plugin-scaffold-react-component): scaffold to create react comp
  packages/cli-plugin-scaffold-admin-app-module/template/package.json
  packages/cli-plugin-scaffold-graphql-service/template/package.json
  packages/cli-plugin-scaffold-react-component/.babelrc.js
  packages/cli-plugin-scaffold-react-component/CHANGELOG.md
  packages/cli-plugin-scaffold-react-component/LICENSE
  packages/cli-plugin-scaffold-react-component/README.md
  packages/cli-plugin-scaffold-react-component/package.json
  packages/cli-plugin-scaffold-react-component/src/index.ts
  packages/cli-plugin-scaffold-react-component/template/.babelrc.js
  packages/cli-plugin-scaffold-react-component/template/package.json
  packages/cli-plugin-scaffold-react-component/template/src/Target.tsx
  packages/cli-plugin-scaffold-react-component/template/src/index.ts
  packages/cli-plugin-scaffold-react-component/template/tsconfig.build.json
  packages/cli-plugin-scaffold-react-component/template/tsconfig.json
  packages/cli-plugin-scaffold-react-component/tsconfig.build.json
  packages/cli-plugin-scaffold-react-component/tsconfig.json
  packages/cwp-template-aws/template/dependencies.json
  packages/cwp-template-aws/template/webiny.root.js
  webiny.root.js
  yarn.lock
Labels: feature
