Repository webiny/webiny-js, pull requests merged in 2021-05, with the labels that each got.

#1582 fix(app-page-builder): move test formatting styles to theme
  apps/theme/pageBuilder/styles/elements/typography.scss
  packages/app-page-builder/src/editor/components/MediumEditor/index.ts
Labels: bug

#1587 feat: add not found page content
  packages/api-page-builder/src/graphql/crud/install/notFoundPageData.ts
  packages/api-page-builder/src/graphql/crud/system.crud.ts
Labels: bug

#1579 Feat: PB navigator
  apps/admin/code/src/plugins/pageBuilder/editorPlugins.ts
  apps/admin/code/src/plugins/pageBuilder/renderPlugins.ts
  apps/website/code/src/plugins/pageBuilder.ts
  packages/app-page-builder/package.json
  packages/app-page-builder/src/admin/plugins/pageDetails/header/editRevision/EditRevision.tsx
  packages/app-page-builder/src/editor/assets/icons/segment_black_24px.svg
  packages/app-page-builder/src/editor/assets/icons/visibility_off_24px.svg
  packages/app-page-builder/src/editor/components/Editor/DragPreview.tsx
  packages/app-page-builder/src/editor/components/Editor/Toolbar.tsx
  packages/app-page-builder/src/editor/contexts/EventActionHandlerProvider.tsx
  packages/app-page-builder/src/editor/helpers.ts
  packages/app-page-builder/src/editor/plugins/blockEditing/SearchBlocks.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/EditorResponsiveBar.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/Revisions.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/visibility/VisibilitySettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/visibility/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/cell/CellContainer.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/Action.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/addElement/index.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/CollapsableList.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/DragBlockIndicator.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/Navigator.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/StyledComponents.ts
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/TreeView.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/assets/arrow_downward_24px.svg
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/assets/arrow_upward_24px.svg
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/assets/drag_indicator_24px.svg
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/assets/unfold_less_24px.svg
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/assets/unfold_more_24px.svg
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/index.tsx
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/navigatorHooks.ts
  packages/app-page-builder/src/editor/recoil/actions/cloneElement/action.ts
  packages/app-page-builder/src/editor/recoil/actions/createElement/action.ts
  packages/app-page-builder/src/editor/recoil/actions/deleteElement/action.ts
  packages/app-page-builder/src/editor/recoil/actions/index.ts
  packages/app-page-builder/src/editor/recoil/actions/moveBlock/action.ts
  packages/app-page-builder/src/editor/recoil/actions/moveBlock/event.ts
  packages/app-page-builder/src/editor/recoil/actions/moveBlock/index.ts
  packages/app-page-builder/src/editor/recoil/actions/moveBlock/plugin.ts
  packages/app-page-builder/src/editor/recoil/actions/moveBlock/types.ts
  packages/app-page-builder/src/editor/recoil/actions/plugins.ts
  packages/app-page-builder/src/editor/recoil/actions/updateElement/action.ts
  packages/app-page-builder/src/editor/recoil/actions/updateElement/types.ts
  packages/app-page-builder/src/editor/recoil/actions/updateElementTree/event.ts
  packages/app-page-builder/src/editor/recoil/actions/updateElementTree/index.ts
  packages/app-page-builder/src/editor/recoil/actions/updateElementTree/plugin.ts
  packages/app-page-builder/src/render/components/ElementRoot.tsx
  packages/app-page-builder/src/render/plugins/elementSettings/visibility/index.ts
  packages/app-page-builder/src/types.ts
  packages/app-page-builder/webiny.config.js
  packages/cwp-template-aws/template/apps/admin/code/src/plugins/pageBuilder/editorPlugins.ts
  packages/cwp-template-aws/template/apps/admin/code/src/plugins/pageBuilder/renderPlugins.ts
  packages/cwp-template-aws/template/apps/website/code/src/plugins/pageBuilder.ts
  yarn.lock
Labels: feature

#1617 Add sizes attribute to the Image component
  packages/app/src/plugins/image.tsx
Labels: improvement

#1622 Improve error handling in handler
  api/code/graphql/src/index.ts
  apps/admin/code/src/components/apolloClient.ts
  packages/app/package.json
  packages/app/src/graphql/createErrorOverlay/ErrorOverlay.tsx
  packages/app/src/graphql/createErrorOverlay/StyledComponents.tsx
  packages/app/src/graphql/createErrorOverlay/assets/close_24px.svg
  packages/app/src/graphql/createErrorOverlay/index.tsx
  packages/app/src/graphql/createNetworkErrorLink.ts
  packages/app/src/graphql/index.ts
  packages/cwp-template-aws/template/api/code/graphql/src/index.ts
  packages/cwp-template-aws/template/apps/admin/code/src/components/apolloClient.ts
  packages/cwp-template-aws/template/example.env
  packages/cwp-template-aws/template/example.keep.env
  packages/handler-aws/src/index.ts
  packages/handler-graphql/src/createGraphQLHandler.ts
  packages/handler-http/package.json
  packages/handler-http/src/index.ts
  packages/handler-http/src/types.ts
  packages/project-utils/bundling/app/index.js
  yarn.lock
Labels: improvement

#1639 Fix: update createHandler usage in headless cms
  api/code/graphql/src/index.ts
  api/code/headlessCMS/src/index.ts
  packages/api-headless-cms/src/content/graphQLHandlerFactory.ts
  packages/cwp-template-aws/template/api/code/graphql/src/index.ts
  packages/cwp-template-aws/template/api/code/headlessCMS/src/index.ts
  packages/handler-http/src/index.ts
  packages/handler-http/src/types.ts
Labels: improvement

#1601 feat(where-parser): standardize the where input object to ease the querying
  packages/api-headless-cms/__tests__/contentAPI/latestEntries.test.ts
  packages/where-parser/.babelrc.js
  packages/where-parser/LICENSE
  packages/where-parser/README.md
  packages/where-parser/__tests__/conditions.test.ts
  packages/where-parser/__tests__/conditions/between.test.ts
  packages/where-parser/__tests__/conditions/contains.test.ts
  packages/where-parser/__tests__/conditions/eq.test.ts
  packages/where-parser/__tests__/conditions/gt.test.ts
  packages/where-parser/__tests__/conditions/gte.test.ts
  packages/where-parser/__tests__/conditions/in.test.ts
  packages/where-parser/__tests__/conditions/lt.test.ts
  packages/where-parser/__tests__/conditions/lte.test.ts
  packages/where-parser/__tests__/parsers/keyParser.test.ts
  packages/where-parser/__tests__/whereParser.test.ts
  packages/where-parser/jest.config.js
  packages/where-parser/package.json
  packages/where-parser/src/conditions/between.ts
  packages/where-parser/src/conditions/contains.ts
  packages/where-parser/src/conditions/eq.ts
  packages/where-parser/src/conditions/gt.ts
  packages/where-parser/src/conditions/gte.ts
  packages/where-parser/src/conditions/in.ts
  packages/where-parser/src/conditions/index.ts
  packages/where-parser/src/conditions/lt.ts
  packages/where-parser/src/conditions/lte.ts
  packages/where-parser/src/index.ts
  packages/where-parser/src/parsers/keyParser.ts
  packages/where-parser/src/types.ts
  packages/where-parser/tsconfig.build.json
  packages/where-parser/tsconfig.json
  packages/where-parser/webiny.config.js
  yarn.lock
Labels: feature

#1660 feat(api-headless-cms): add createdBy, ownedBy and entryId filtering
  packages/api-headless-cms-ddb-es/README.md
  packages/api-headless-cms-ddb-es/__tests__/__api__/README.md
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb/README.md
  packages/api-headless-cms-ddb/__tests__/__api__/README.md
  packages/api-headless-cms-ddb/src/operations/entry/systemFields.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/latestEntries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.apiKey.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.apiKey.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.read.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.read.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.read.ts
  packages/api-headless-cms/__tests__/utils/graphql/contentModel.ts
  packages/api-headless-cms/__tests__/utils/graphql/contentModelGroup.ts
  packages/api-headless-cms/__tests__/utils/useArticleManageHandler.ts
  packages/api-headless-cms/__tests__/utils/useArticleReadHandler.ts
  packages/api-headless-cms/__tests__/utils/useCategoryManageHandler.ts
  packages/api-headless-cms/__tests__/utils/useCategoryReadHandler.ts
  packages/api-headless-cms/src/content/plugins/schema/baseSchema.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModelGroups.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModels.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/createReadSDL.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/commonFieldResolvers.ts
  packages/api-headless-cms/src/content/plugins/utils/renderGetFilterFields.ts
  packages/api-headless-cms/src/content/plugins/utils/renderListFilterFields.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#1662 refactor(api-headless-cms-ddb-es): loosen elasticsearch query types
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/helpers.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/between.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/equal.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/in.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/not.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notBetween.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notContains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notIn.test.ts
  packages/api-headless-cms-ddb-es/package.json
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/types.ts
  packages/api-headless-cms-ddb/package.json
  packages/api-headless-cms/package.json
  packages/api-headless-cms/tsconfig.build.json
  packages/api-headless-cms/tsconfig.json
  packages/api-page-builder/src/graphql/crud/utils/getNormalizedListPagesArgs.ts
  packages/api-plugin-elastic-search-client/src/types.ts
  yarn.lock
Labels: improvement

#1667 fix(api-headless-cms-ddb-es): add missing property
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/helpers.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/between.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/equal.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/in.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/not.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notBetween.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notContains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notIn.test.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
Labels: bug

#1669 refactor(api-plugin-elastic-search-client): use elastic-ts package for ES types
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/helpers.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/between.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/equal.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/in.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/not.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notBetween.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notContains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notIn.test.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/not.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/notBetween.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/notContains.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/notIn.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/types.ts
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/crud/utils/getNormalizedListPagesArgs.ts
  packages/api-page-builder/src/plugins/SearchPagesPlugin.ts
  packages/api-plugin-elastic-search-client/package.json
  packages/api-plugin-elastic-search-client/src/types.ts
  yarn.lock
Labels: feature
