Repository webiny/webiny-js, pull requests merged in 2021-07, with the labels that each got.

#1751 refactor(api-headless-cms-ddb): ddb plugins
  packages/api-file-manager/package.json
  packages/api-headless-cms-ddb/__tests__/plugins/filters/filters.test.ts
  packages/api-headless-cms-ddb/package.json
  packages/api-headless-cms-ddb/src/dynamoDb/path/ref.ts
  packages/api-headless-cms-ddb/src/dynamoDb/transformValue/datetime.ts
  packages/api-headless-cms-ddb/src/filters/between.ts
  packages/api-headless-cms-ddb/src/filters/contains.ts
  packages/api-headless-cms-ddb/src/filters/eq.ts
  packages/api-headless-cms-ddb/src/filters/gt.ts
  packages/api-headless-cms-ddb/src/filters/gte.ts
  packages/api-headless-cms-ddb/src/filters/in.ts
  packages/api-headless-cms-ddb/src/filters/index.ts
  packages/api-headless-cms-ddb/src/filters/lt.ts
  packages/api-headless-cms-ddb/src/filters/lte.ts
  packages/api-headless-cms-ddb/src/index.ts
  packages/api-headless-cms-ddb/src/operations/entry/utils.ts
  packages/api-headless-cms-ddb/src/types.ts
  packages/api-headless-cms-ddb/tsconfig.build.json
  packages/api-headless-cms-ddb/tsconfig.json
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/db-dynamodb/__tests__/assignFields.test.ts
  packages/db-dynamodb/src/plugins/assignFields.ts
  yarn.lock
Labels: improvement

#1757 fix(v5): upgrade elasticsearch package
  packages/cli/commands/upgrade/upgrades/5.10.0/index.js
  packages/cli/commands/upgrade/upgrades/5.10.0/upgradeApiFileManager.js
  packages/db-dynamodb/package.json
  yarn.lock
Labels: bug

#1754 refactor(api-headless-cms-ddb-es): reuse existing elastic packages
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/between.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/equal.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/gte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/in.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/lte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/normalizeContains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/not.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notBetween.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notContains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/operators/notIn.test.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/index.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/between.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/contains.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/equal.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/gt.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/gte.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/in.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/lt.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/lte.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/not.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/notBetween.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/notContains.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/operators/notIn.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchLimit.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/helpers/fields.ts
  packages/api-headless-cms-ddb-es/src/helpers/index.ts
  packages/api-headless-cms-ddb-es/src/helpers/operatorPluginsList.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/CmsContentEntryDynamoElastic.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/fields.ts
  packages/api-headless-cms-ddb-es/src/utils.ts
  packages/api-headless-cms-ddb-es/tsconfig.build.json
  packages/api-headless-cms-ddb-es/tsconfig.json
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
Labels: improvement

#1775 fix(api-headless-cms): get published entry revision from referenced field
  packages/api-headless-cms-ddb-es/src/operations/entry/CmsContentEntryDynamoElastic.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/dataLoaders.ts
  packages/api-headless-cms-ddb/src/definitions/entry.ts
  packages/api-headless-cms-ddb/src/definitions/table.ts
  packages/api-headless-cms-ddb/src/operations/entry/CmsContentEntryDynamo.ts
  packages/api-headless-cms-ddb/src/operations/entry/dataLoaders.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/references.test.ts
  packages/api-headless-cms/__tests__/utils/setup.ts
Labels: bug

#1741 Feat: Use fine-grained policies for AWS resources
  api/pulumi/dev/defaultLambdaRole.ts
  api/pulumi/dev/elasticSearch.ts
  api/pulumi/dev/fileManager.ts
  api/pulumi/dev/graphql.ts
  api/pulumi/dev/headlessCMS.ts
  api/pulumi/dev/index.ts
  api/pulumi/dev/pageBuilder.ts
  api/pulumi/dev/policies.ts
  api/pulumi/dev/prerenderingService.ts
  api/pulumi/prod/cognito.ts
  api/pulumi/prod/defaultLambdaRole.ts
  api/pulumi/prod/dynamoDb.ts
  api/pulumi/prod/elasticSearch.ts
  api/pulumi/prod/fileManager.ts
  api/pulumi/prod/graphql.ts
  api/pulumi/prod/headlessCMS.ts
  api/pulumi/prod/index.ts
  api/pulumi/prod/pageBuilder.ts
  api/pulumi/prod/policies.ts
  api/pulumi/prod/prerenderingService.ts
  docs/AWS_USER_POLICY_DOCUMENT.js
  docs/CWP_POLICY_CLOUDFORMATION_TEMPLATE.json
Labels: improvement

#1801 fix(cli): put i18n-ddb package version to current context.version
  packages/api-i18n/src/graphql/crud/locales.crud.ts
  packages/app-i18n/src/admin/views/locales/hooks/useLocaleForm.ts
  packages/cli/commands/upgrade/upgrades/5.11.0/index.js
  packages/cli/commands/upgrade/upgrades/utils.js
Labels: bug

#1814 feat(cli): cms object field upgrade
  packages/cli/commands/upgrade/upgrades/5.11.0/index.js
  packages/cli/commands/upgrade/upgrades/5.11.0/upgradeObjectField.js
  packages/cli/commands/upgrade/upgrades/utils.js
Labels: feature

#1810 Add improvements to object field UI
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/longText/longText.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/longText/longTexts.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/object/StyledComponents.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/object/multipleObjects.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/object/singleObject.tsx
Labels: improvement

#1811 Fix/issue 1799
  packages/app-form-builder/src/admin/plugins/editor/formSettings/components/graphql.ts
  packages/app-form-builder/src/admin/plugins/settings/components/graphql.ts
Labels: bug

#1836 fix(app-headless-cms): date transformer field no value error
  packages/app-headless-cms/src/admin/plugins/transformers/dateTransformer.ts
Labels: bug

#1838 fix(api-headless-cms): request review
  packages/api-headless-cms-ddb-es/src/operations/entry/CmsContentEntryDynamoElastic.ts
  packages/api-headless-cms/__tests__/contentAPI/requestReview.test.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
Labels: bug

#1820 fix(api-headless-cms): context loading
  packages/api-headless-cms/__tests__/contentAPI/httpOptions.test.ts
  packages/api-headless-cms/__tests__/utils/useGqlHandler.ts
  packages/api-headless-cms/src/content/contextSetup.ts
  packages/api-headless-cms/src/content/index.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModelGroup.crud.ts
  packages/api-headless-cms/src/content/plugins/modelManager/index.ts
  packages/api-headless-cms/src/plugins/crud/settings.crud.ts
  packages/api-headless-cms/src/plugins/crud/system.crud.ts
Labels: bug

#1821 feat: compress the data that goes into es ddb table
  api/code/dynamoToElastic/src/index.ts
  api/code/dynamoToElastic/tsconfig.json
  api/code/graphql/src/index.ts
  api/code/headlessCMS/src/index.ts
  api/code/pageBuilder/updateSettings/tsconfig.json
  packages/api-dynamodb-to-elasticsearch/src/handler/index.ts
  packages/api-elasticsearch/package.json
  packages/api-elasticsearch/src/compression.ts
  packages/api-elasticsearch/src/plugins/GzipCompression.ts
  packages/api-elasticsearch/src/plugins/definition/CompressionPlugin.ts
  packages/api-file-manager-ddb-es/__tests__/__api__/environment.js
  packages/api-file-manager-ddb-es/src/operations/files/FilesStorageOperations.ts
  packages/api-headless-cms-ddb-es/__tests__/__api__/environment.js
  packages/api-headless-cms-ddb-es/package.json
  packages/api-headless-cms-ddb-es/src/operations/entry/CmsContentEntryDynamoElastic.ts
  packages/api-headless-cms-ddb-es/tsconfig.build.json
  packages/api-headless-cms-ddb-es/tsconfig.json
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/cli/commands/upgrade/upgrades/5.12.0/index.js
  packages/cli/commands/upgrade/upgrades/5.12.0/upgradeElasticsearch.js
  packages/cwp-template-aws/template/api/code/dynamoToElastic/src/index.ts
  packages/cwp-template-aws/template/api/code/graphql/src/index.ts
  packages/cwp-template-aws/template/api/code/headlessCMS/src/index.ts
  packages/db-dynamodb/src/utils/filter.ts
  yarn.lock
Labels: feature
