Repository webiny/webiny-js, pull requests merged in 2021-11, with the labels that each got.

#2004 feat(cli): upgrade pulumi in 5.17.0
  packages/api-page-builder-import-export/src/graphql/crud/pages.crud.ts
  packages/api-page-builder-import-export/src/graphql/graphql/pages.gql.ts
  packages/api-page-builder-import-export/src/graphql/types.ts
  packages/api-page-builder-import-export/src/importPages/create/index.ts
  packages/app-graphql-playground/src/plugins/placeholder.graphql
  packages/app-page-builder/src/admin/graphql/pageImportExport.gql.ts
  packages/app-page-builder/src/admin/views/Pages/PagesDataList.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useImportPage.ts
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ExportPageButton/index.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ExportPageButton/useExportPage.ts
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ExportPageButton/useExportPageDialog.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ExportPageButton/useExportPageRevisionSelectorDialog.tsx
  packages/cli/commands/upgrade/upgrades/5.17.0/index.js
  packages/cli/commands/upgrade/upgrades/5.17.0/security.js
  packages/cli/commands/upgrade/upgrades/utils.js
Labels: feature

#2006 Fix: Menu component
  packages/ui/src/Menu/Menu.tsx
Labels: bug

#1987 CI/CD - Run Jest Tests in Parallel
  .github/workflows/nextPush.yml
  .github/workflows/pullRequests.yml
  .github/workflows/releaseNext.disabled
  .github/workflows/v5Push.yml
  scripts/listPackagesWithTests.js
  scripts/utils/getPackages.js
Labels: work-in-progress (wip), improvement

#2007 Fix: Incorrect rendering of Grid element in editor
  packages/app-page-builder/src/editor/plugins/elements/grid/Grid.tsx
Labels: bug

#1997 fix(app-page-builder): starting point to fix #1994 `Broken sort settings field for List of Pages`
  packages/app-page-builder/src/editor/plugins/elements/pagesList/PagesList.tsx
  packages/app-page-builder/src/editor/plugins/elements/pagesList/graphql.ts
  packages/app-page-builder/src/render/plugins/elements/pagesList/PagesList.tsx
  packages/app-page-builder/src/render/plugins/elements/pagesList/graphql.ts
Labels: bug

#2009 CI/CD – Run Cypress Tests in Parallel
  .github/workflows/nextPush.yml
  .github/workflows/rebuildCache.yml
  .github/workflows/v5Push.yml
  packages/api-prerendering-service/src/utils/getStorageFolder.ts
  packages/create-webiny-project/index.js
  packages/create-webiny-project/utils/createProject.js
  scripts/listCypressTestsFolders.js
Labels: work-in-progress (wip), improvement

#2019 feat(api-headless-cms): move all crud ops to root of context cms object
  packages/api-headless-cms-ddb-es/src/index.ts
  packages/api-headless-cms-dynamic-pages/src/GetEntryDataSource.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/lifecycleHooks.ts
  packages/api-headless-cms/src/content/graphQLHandlerFactory.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry/markLockedFields.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/afterCreate.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/afterDelete.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/afterUpdate.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModelGroup.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/index.ts
  packages/api-headless-cms/src/content/plugins/internalSecurity/InternalAuthenticationPlugin.ts
  packages/api-headless-cms/src/content/plugins/modelManager/DefaultContentModelManager.ts
  packages/api-headless-cms/src/content/plugins/schema/contentEntries.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModelGroups.ts
  packages/api-headless-cms/src/content/plugins/schema/contentModels.ts
  packages/api-headless-cms/src/content/plugins/schema/createManageResolvers.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveCreate.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveCreateFrom.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveDelete.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveGet.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveGetByIds.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveGetRevisions.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveList.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolvePublish.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveRequestChanges.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveRequestReview.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveUnpublish.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveUpdate.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/preview/resolveGet.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/preview/resolveList.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/read/resolveGet.ts
  packages/api-headless-cms/src/content/plugins/schema/resolvers/read/resolveList.ts
  packages/api-headless-cms/src/content/plugins/schema/schemaPlugins.ts
  packages/api-headless-cms/src/plugins/crud/index.ts
  packages/api-headless-cms/src/plugins/crud/system.crud.ts
  packages/api-headless-cms/src/plugins/graphql/system.ts
  packages/api-headless-cms/src/plugins/upgrades/v5.5.0/index.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#1989 Optimize Deployment of Admin Area Application
  .github/workflows/nextPush.yml
  apps/admin/cli/deploy.ts
  apps/admin/cli/index.ts
  apps/admin/pulumi/app.ts
  apps/admin/pulumi/index.ts
  apps/website/cli/deploy.ts
  apps/website/cli/index.ts
  apps/website/cli/renderWebsite.ts
  apps/website/cli/updatePbSettings.ts
  packages/api-page-builder/package.json
  packages/api-page-builder/src/cli/index.js
  packages/cli-plugin-deploy-pulumi/commands/deploy.js
  packages/cli-plugin-deploy-pulumi/utils/aws/uploadFolderToS3.js
  packages/cwp-template-aws/template/common/apps/admin/cli/deploy.ts
  packages/cwp-template-aws/template/common/apps/admin/cli/index.ts
  packages/cwp-template-aws/template/common/apps/admin/pulumi/app.ts
  packages/cwp-template-aws/template/common/apps/admin/pulumi/index.ts
  packages/cwp-template-aws/template/common/apps/website/cli/deploy.ts
  packages/cwp-template-aws/template/common/apps/website/cli/index.ts
  packages/cwp-template-aws/template/common/apps/website/cli/renderWebsite.ts
  packages/cwp-template-aws/template/common/apps/website/cli/updatePbSettings.ts
  packages/cwp-template-aws/template/common/webiny.project.ts
  webiny.project.ts
  yarn.lock
Labels: work-in-progress (wip), improvement

#2014 Fix: PB assorted bugs
  apps/theme/package.json
  apps/theme/pageBuilder/components/Menu.tsx
  apps/theme/pageBuilder/components/MobileHeader.tsx
  apps/theme/pageBuilder/styles/elements/header-nav.scss
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/app-admin/src/plugins/menu/documentation.tsx
  packages/app-admin/src/plugins/menu/renderers/MenuLinkRenderer.tsx
  packages/app-admin/src/plugins/menu/slack.tsx
  packages/app-admin/src/plugins/menu/source.tsx
  packages/app-admin/src/ui/elements/NavigationMenuElement.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/header/deletePage/DeletePage.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/pageRevisions/Revision.tsx
  packages/cwp-template-aws/template/common/apps/theme/package.json
  packages/cwp-template-aws/template/common/apps/theme/pageBuilder/components/Menu.tsx
  packages/cwp-template-aws/template/common/apps/theme/pageBuilder/components/MobileHeader.tsx
  packages/cwp-template-aws/template/common/apps/theme/pageBuilder/styles/elements/header-nav.scss
  yarn.lock
Labels: improvement

#2026 feat(api-headless-cms): long text compression
  packages/api-dynamodb-to-elasticsearch/src/handler/index.ts
  packages/api-elasticsearch/__tests__/plugins/GzipCompression.test.ts
  packages/api-elasticsearch/package.json
  packages/api-elasticsearch/src/plugins/GzipCompression.ts
  packages/api-elasticsearch/tsconfig.build.json
  packages/api-elasticsearch/tsconfig.json
  packages/api-headless-cms-ddb-es/__tests__/entryIndexing.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/indexing/objectIndexing.test.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/index.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/date.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/longText.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/richText.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/indexing/index.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/indexing/longTextIndexing.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/indexing/objectIndexing.ts
  packages/api-headless-cms-ddb-es/src/helpers/entryIndexHelpers.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
  packages/api-headless-cms-ddb-es/src/types.ts
  packages/api-headless-cms-ddb/src/dynamoDb/index.ts
  packages/api-headless-cms-ddb/src/dynamoDb/storage/date.ts
  packages/api-headless-cms-ddb/src/dynamoDb/storage/longText.ts
  packages/api-headless-cms-ddb/src/dynamoDb/storage/richText.ts
  packages/api-headless-cms-ddb/src/operations/entry/index.ts
  packages/api-headless-cms-ddb/src/operations/entry/utils.ts
  packages/api-headless-cms/__tests__/contentAPI/fieldValidations.test.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.noValidation.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/sorting.test.ts
  packages/api-headless-cms/__tests__/utils/useFruitManageHandler.ts
  packages/api-headless-cms/__tests__/utils/useFruitReadHandler.ts
  packages/api-headless-cms/src/content/plugins/storage/StorageTransformPlugin.ts
  packages/api-headless-cms/src/content/plugins/storage/default.ts
  packages/api-headless-cms/src/content/plugins/storage/object.ts
  packages/api-headless-cms/src/content/plugins/utils/entryStorage.ts
  packages/api-headless-cms/src/index.ts
  packages/api-headless-cms/src/types.ts
  packages/api-upgrade/__tests__/upgrade.test.ts
  packages/api-upgrade/src/index.ts
  packages/utils/package.json
  packages/utils/src/compression/gzip.ts
  yarn.lock
Labels: feature

#2031 feat(api-headless-cms): add get and list before events
  packages/api-elasticsearch/src/plugins/definition/ElasticsearchBodyModifierPlugin.ts
  packages/api-elasticsearch/src/plugins/definition/ElasticsearchQueryModifierPlugin.ts
  packages/api-elasticsearch/src/plugins/definition/ElasticsearchSortModifierPlugin.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchBodyModifierPlugin.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchFieldPlugin.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchQueryModifierPlugin.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchSortModifierPlugin.ts
  packages/api-headless-cms-ddb-es/src/types.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntryHooks.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/lifecycleHooks.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/content/plugins/modelManager/DefaultCmsModelManager.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#2029 fix(api-file-manager): search by tags or filename
  packages/api-file-manager-ddb-es/__tests__/__api__/environment.js
  packages/api-file-manager-ddb-es/package.json
  packages/api-file-manager-ddb-es/src/definitions/tableElasticsearch.ts
  packages/api-file-manager-ddb-es/src/operations/configurations.ts
  packages/api-file-manager-ddb-es/src/operations/files/FilesStorageOperations.ts
  packages/api-file-manager-ddb-es/src/operations/files/body.ts
  packages/api-file-manager-ddb-es/src/operations/system/FileManagerInstallationPlugin.ts
  packages/api-file-manager-ddb-es/src/upgrades/v5.0.0/index.ts
  packages/api-file-manager-ddb/package.json
  packages/api-file-manager-ddb/src/operations/files/FilesStorageOperations.ts
  packages/api-file-manager/__tests__/files.test.ts
  packages/api-file-manager/__tests__/useGqlHandler.ts
  packages/api-file-manager/src/plugins/crud/files.crud.ts
  packages/api-file-manager/src/types.ts
  packages/db-dynamodb/src/plugins/filters/contains.ts
  scripts/listPackagesWithTests.js
  yarn.lock
Labels: bug

#2033 fix(api-headless-cms): model id checks
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.modelId.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.uniqueModelId.test.ts
  packages/api-headless-cms/src/content/plugins/crud/contentModel/beforeCreate.ts
  packages/app-headless-cms/src/admin/views/contentModels/NewContentModelDialog.tsx
Labels: bug

#2037 feat(api-headless-cms): load model and entry crud in admin
  packages/api-headless-cms/src/content/plugins/crud/index.ts
  packages/api-headless-cms/src/plugins/crud/index.ts
  packages/project-utils/bundling/function/createBuildConfig.js
  packages/project-utils/bundling/function/createWatchConfig.js
Labels: feature

#2039 fix(api): pulumi throwing error after version update
  api/pulumi/dev/elasticSearch.ts
  api/pulumi/prod/elasticSearch.ts
Labels: bug

#2042 Fix/issue 1927
  packages/api-headless-cms/__tests__/contentAPI/lockedFields.test.ts
  packages/api-headless-cms/__tests__/contentAPI/model.delete.test.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry/afterDelete.ts
  packages/api-headless-cms/src/content/plugins/crud/contentEntry/markLockedFields.ts
  packages/api-headless-cms/src/content/plugins/crud/index.ts
  packages/api-headless-cms/src/plugins/crud/index.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#2046 feat(app-headless-cms): ref field validators
  packages/app-admin/src/components/FileManager.tsx
  packages/app-admin/src/components/FileManager/FileManagerView.tsx
  packages/app-headless-cms/src/admin/plugins/definitions/CmsEditorFieldValidatorFileTypePlugin.ts
  packages/app-headless-cms/src/admin/plugins/definitions/CmsFieldValidatorFileTypePlugin.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/File.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileField.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileFields.tsx
  packages/app-headless-cms/src/admin/plugins/fields/file.tsx
  packages/app-headless-cms/src/admin/plugins/fields/ref.tsx
  packages/app-headless-cms/src/types.ts
  packages/form/src/FormNew.tsx
Labels: feature
