Repository webiny/webiny-js, pull requests merged in 2021-04, with the labels that each got.

#1546 Feat: add a sand alone CTA for File Manager app
  apps/admin/code/src/plugins/admin.ts
  packages/app-admin/src/components/FileManager.tsx
  packages/app-admin/src/components/FileManager/File.tsx
  packages/app-admin/src/components/FileManager/FileDetails.tsx
  packages/app-admin/src/components/FileManager/FileManagerView.tsx
  packages/app-admin/src/components/FileManager/icons/content_copy-black-24px.svg
  packages/app-admin/src/plugins/menu/fileManager.tsx
  packages/cwp-template-aws/template/apps/admin/code/src/plugins/admin.ts
Labels: improvement

#1550 fix: update `ImagesList` element type
  packages/app-page-builder/src/editor/plugins/elements/imagesList/index.tsx
Labels: bug

#1542 Fix: Rich text editor visual bug
  apps/theme/richTextEditor/styles.scss
  packages/app-headless-cms/src/admin/plugins/contentDetails/contentRevisions/useRevision.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/File.tsx
  packages/ui/src/ImageUpload/Image.tsx
Labels: bug

#1548 fix(app-admin): update list styles
  packages/ui/src/AutoComplete/AutoComplete.tsx
  packages/ui/src/AutoComplete/MultiAutoComplete.tsx
Labels: bug

#1543 Fix: UI improvements in new account form
  packages/app-plugin-security-cognito/src/identityProvider/cognitoPasswordValidator.ts
  packages/app-plugin-security-cognito/src/identityProvider/index.tsx
  packages/app-plugin-security-cognito/src/types.ts
  packages/app-security-tenancy/src/views/Users/UsersForm.tsx
Labels: bug

#1556 feat(api-security-tenancy): cache permissions and users
  packages/api-security-tenancy/package.json
  packages/api-security-tenancy/src/authorization/anonymous.ts
  packages/api-security-tenancy/src/authorization/apiKey.ts
  packages/api-security-tenancy/src/authorization/user.ts
  packages/api-security-tenancy/src/crud/users.crud.ts
  packages/api-security-tenancy/tsconfig.build.json
  packages/api-security-tenancy/tsconfig.json
  yarn.lock
Labels: feature

#1558 feat(api-security-tenancy): cache keys are based on tenant + identity
  packages/api-security-tenancy/src/authorization/apiKey.ts
  packages/api-security-tenancy/src/authorization/user.ts
Labels: feature

#1569 Prerendering Related Fixes
  api/pulumi/dev/prerenderingService.ts
  apps/website/code/src/components/Page/index.tsx
  apps/website/code/src/plugins/apolloLinks.ts
  apps/website/code/src/plugins/index.ts
  packages/api-page-builder/src/cli/index.js
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/prerendering.ts
  packages/api-page-builder/src/graphql/types.ts
  packages/api-prerendering-service-aws/src/render/index.ts
  packages/api-prerendering-service/__tests__/render/handlers/render/renderUrl.test.ts
  packages/api-prerendering-service/package.json
  packages/api-prerendering-service/src/render/index.ts
  packages/api-prerendering-service/src/render/injectApolloState.ts
  packages/api-prerendering-service/src/render/injectNotFoundPageFlag.ts
  packages/api-prerendering-service/src/render/injectRenderId.ts
  packages/api-prerendering-service/src/render/injectRenderTs.ts
  packages/api-prerendering-service/src/render/injectTenantLocale.ts
  packages/api-prerendering-service/src/render/renderUrl.ts
  packages/api-prerendering-service/src/render/types.ts
  packages/app-page-builder/package.json
  packages/app-page-builder/src/admin/hooks/usePageBuilderSettings/usePageBuilderSettings.ts
  packages/app-page-builder/tsconfig.build.json
  packages/app-page-builder/tsconfig.json
  packages/cli-plugin-deploy-pulumi/commands/index.js
  packages/cli-plugin-deploy-pulumi/commands/watch.js
  packages/cli/utils/getProjectApplication.js
  packages/cwp-template-aws/template/apps/website/code/src/plugins/apolloLinks.ts
  packages/cwp-template-aws/template/apps/website/code/src/plugins/index.ts
  yarn.lock
Labels: bug

#1577 FileManager - ensure the default `application/octet-stream` MIME type is used, if none provided
  packages/app-admin/src/components/FileManager/FileManagerView.tsx
Labels: bug
