Repository webiny/webiny-js, pull requests merged in 2022-12, with the labels that each got.

#2813 feat(api-headless-cms-ddb-es): nested and filter
  packages/api-headless-cms-ddb-es/__tests__/filtering.test.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/helpers/fields.ts
  packages/api-headless-cms-ddb-es/src/helpers/index.ts
  packages/api-headless-cms-ddb-es/src/helpers/searchPluginsList.ts
  packages/api-headless-cms-ddb-es/src/index.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/body.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/exec.ts
  packages/api-headless-cms-ddb/src/index.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlAndQueries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/nestedQueries.test.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#2814 Page Builder Blocks V2.1
  apps/theme/pageBuilder/styles/base.scss
  apps/website/src/components/Page/Render.tsx
  apps/website/src/components/Page/graphql.ts
  packages/api-page-builder-so-ddb-es/src/definitions/settingsEntity.ts
  packages/api-page-builder-so-ddb/src/definitions/settingsEntity.ts
  packages/api-page-builder/src/graphql/graphql/settings.gql.ts
  packages/api-page-builder/src/types.ts
  packages/api-page-builder/src/utils/models/DefaultSettings.model.ts
  packages/app-admin/src/ui/elements/form/FileManagerElement/FileManagerElementRenderer.tsx
  packages/app-page-builder/src/admin/hooks/usePageBuilderSettings/usePageBuilderSettings.ts
  packages/app-page-builder/src/admin/utils/createBlockCategoryPlugin.tsx
  packages/app-page-builder/src/admin/views/BlockCategories/BlockCategoriesDataList.tsx
  packages/app-page-builder/src/admin/views/PageBlocks/BlocksByCategoriesDataList.tsx
  packages/app-page-builder/src/admin/views/PageBlocks/PageBlocks.tsx
  packages/app-page-builder/src/admin/views/PageBlocks/PageBlocksDataList.tsx
  packages/app-page-builder/src/blockEditor/components/elementSettingsTab/ElementNotLinked.tsx
  packages/app-page-builder/src/blockEditor/components/elementSettingsTab/VariableSettings.tsx
  packages/app-page-builder/src/blockEditor/config/BlockEditorConfig.tsx
  packages/app-page-builder/src/blockEditor/config/ToolbarActionsPlugin.tsx
  packages/app-page-builder/src/blockEditor/config/editorBar/BackButton/BackButton.tsx
  packages/app-page-builder/src/blockEditor/config/editorBar/SaveBlockButton/SaveBlockButton.tsx
  packages/app-page-builder/src/blockEditor/config/eventActions/EventActionPlugins.tsx
  packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/event.ts
  packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/getPreviewImage.ts
  packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/index.ts
  packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/saveBlockAction.ts
  packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/toggleSaveBlockStateAction.ts
  packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/types.ts
  packages/app-page-builder/src/blockEditor/config/eventActions/updateBlockAction.ts
  packages/app-page-builder/src/blockEditor/createStateInitializer.ts
  packages/app-page-builder/src/blockEditor/state/blockAtom.ts
  packages/app-page-builder/src/editor/components/Editor/Sidebar/ElementSettingsTabContent.tsx
  packages/app-page-builder/src/editor/components/Editor/Toolbar.tsx
  packages/app-page-builder/src/editor/index.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/action/ActionSettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/advanced/ElementSettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/components/SelectField.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/save/SaveDialog/graphql.ts
  packages/app-page-builder/src/editor/plugins/elements/button/ButtonContainer.tsx
  packages/app-page-builder/src/editor/plugins/elements/button/ButtonSettingsV2.tsx
  packages/app-page-builder/src/editor/plugins/elements/button/index.tsx
  packages/app-page-builder/src/modules/WebsiteSettings/WebsiteSettings.tsx
  packages/app-page-builder/src/modules/WebsiteSettings/graphql.ts
  packages/app-page-builder/src/modules/WebsiteSettings/settingsGroups/HtmlTags.tsx
  packages/app-page-builder/src/pageEditor/config/BlockElementSidebarPlugin.tsx
  packages/app-page-builder/src/render/components/WebsiteScripts.tsx
  packages/app-page-builder/src/render/plugins/elements/button/Button.tsx
  packages/app-page-builder/src/render/utils.ts
  packages/app-page-builder/src/types.ts
  packages/cwp-template-aws/template/common/apps/theme/pageBuilder/styles/base.scss
  packages/cwp-template-aws/template/common/apps/website/src/components/Page/Render.tsx
  packages/cwp-template-aws/template/common/apps/website/src/components/Page/graphql.ts
  packages/react-router/package.json
  packages/ui/src/CodeEditor/CodeEditor.tsx
  yarn.lock
Labels: umbrella ☂️

#2821 test(api-headless-cms): complex and filtering
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/exec.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlAndQueries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.read.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.read.ts
  packages/api-headless-cms/src/graphqlFields/number.ts
Labels: feature

#2825 ci: setup clean release process
  .github/workflows/devPush.yml
  .github/workflows/nextPush.yml
  .github/workflows/pullRequests.yml
  .github/workflows/pullRequestsCommandCypress.yml
  .github/workflows/release.yml
  .github/workflows/stablePush.yml
  .gitignore
  .yarn/patches/@lerna-publish-npm-3.22.1-469707df67
  example.lerna.json
  package.json
  scripts/ConsoleLogger.js
  scripts/release/BetaRelease.js
  scripts/release/LatestRelease.js
  scripts/release/Release.js
  scripts/release/UnstableRelease.js
  scripts/release/VerdaccioRelease.js
  scripts/release/index.js
  scripts/release/releaseTypes.js
  scripts/release/triggerRelease.js
  scripts/releaseLatest.js
  yarn.lock
Labels: CI/CD

#2820 feat(api-headless-cms-ddb-es): nested or filtering
  packages/api-headless-cms-ddb-es/__tests__/filtering.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/between.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/eq.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/gt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/gte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/in.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/lt.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/lte.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/mocks/fields.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/mocks/query.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/not_between.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/not_contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/not_eq.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/not_in.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/not_startsWith.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/startsWith.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/indexing/objectIndexing.test.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/body.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/exec.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/initialQuery.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlOrQueries.test.ts
  packages/api-headless-cms/__tests__/filtering/it.ts
  packages/api-headless-cms/__tests__/filtering/product.test.ts
  packages/api-headless-cms/__tests__/filtering/product/category.ts
  packages/api-headless-cms/__tests__/filtering/product/entries.ts
  packages/api-headless-cms/__tests__/filtering/product/init.ts
  packages/api-headless-cms/__tests__/graphQl/README.md
  packages/api-headless-cms/__tests__/graphQl/helpers.ts
  packages/api-headless-cms/__tests__/types.ts
Labels: feature

#2843 test(api-headless-cms): complex products filtering
  packages/api-headless-cms/__tests__/filtering/product.test.ts
Labels: feature

#2840 fix: page link creation on folder change
  packages/app-page-builder/src/admin/views/Pages/Pages.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useCreatePage.ts
Labels: page-builder

#2852 feat(handler): add compression to response
  packages/handler/package.json
  packages/handler/src/fastify.ts
  yarn.lock
Labels: feature

#2829 feat: add pagination to folder links api and pages table list
  packages/api-folders-so-ddb/src/operations/links.ts
  packages/api-folders/__tests__/graphql/links.ts
  packages/api-folders/__tests__/links.test.ts
  packages/api-folders/__tests__/mocks/links.ts
  packages/api-folders/src/context/links.ts
  packages/api-folders/src/graphql/base.gql.ts
  packages/api-folders/src/graphql/links.gql.ts
  packages/api-folders/src/types.ts
  packages/app-folders/src/contexts/links.tsx
  packages/app-folders/src/graphql/links.gql.ts
  packages/app-folders/src/hooks/useLinks.ts
  packages/app-folders/src/types.ts
  packages/app-page-builder/src/admin/components/Table/Header.tsx
  packages/app-page-builder/src/admin/components/Table/LoadingMore.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/styled.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useGetPages.ts
  packages/app-page-builder/src/types.ts
Labels: page-builder, api

#2857 feat: add folder pubsub events and delete links on folder deletion
  apps/api/graphql/src/index.ts
  apps/api/graphql/tsconfig.json
  packages/api-folders-so-ddb/src/index.ts
  packages/api-folders-so-ddb/src/operations/links.ts
  packages/api-folders/package.json
  packages/api-folders/src/context/folders.ts
  packages/api-folders/src/context/links.ts
  packages/api-folders/src/index.ts
  packages/api-folders/src/subscriptions/afterFolderDelete.ts
  packages/api-folders/src/subscriptions/index.ts
  packages/api-folders/src/types.ts
  packages/api-folders/tsconfig.build.json
  packages/api-folders/tsconfig.json
  packages/cwp-template-aws/template/ddb/apps/api/graphql/src/index.ts
  yarn.lock
Labels: page-builder, api

#2861 fix: update and listen for page cache changes
  packages/app-page-builder/src/admin/views/Pages/cache.ts
  packages/app-page-builder/src/admin/views/Pages/hooks/useGetPages.ts
Labels: page-builder

#2878 fix(api-headless-cms-ddb-es): compress latest entry data on publish
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
Labels: bug

#2871 fix: delete link on page deletetion
  packages/app-page-builder/src/admin/components/Table/Preview.tsx
  packages/app-page-builder/src/admin/components/Table/Row/Page/PageActionDelete.tsx
  packages/app-page-builder/src/admin/components/Table/Table.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/header/deletePage/DeletePage.tsx
  packages/app-page-builder/src/admin/views/Pages/PageDetails.tsx
  packages/app-page-builder/src/admin/views/Pages/Pages.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useDeletePage.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useGetPages.ts
Labels: page-builder

#2842 fix(api-dynamodb-to-elasticsearch): retries for bulk insert
  packages/api-dynamodb-to-elasticsearch/package.json
  packages/api-dynamodb-to-elasticsearch/src/index.ts
  yarn.lock
Labels: feature

#2879 fix: empty folder render and loading flickering
  packages/app-folders/src/components/Dialogs/DialogCreate.tsx
  packages/app-folders/src/components/Dialogs/DialogDelete.tsx
  packages/app-folders/src/components/Dialogs/DialogUpdate.tsx
  packages/app-folders/src/contexts/folders.tsx
  packages/app-folders/src/contexts/links.tsx
  packages/app-folders/src/handlers.tsx
  packages/app-folders/src/hooks/useFolders.ts
  packages/app-folders/src/hooks/useLinks.ts
  packages/app-folders/src/types.ts
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useGetPages.ts
  packages/app-page-builder/src/types.ts
Labels: page-builder

#2889 fix(api-headless-cms-ddb-es): compress latest data on publish
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
Labels: bug

#2905 refactor(api-headless-cms-ddb-es): nested object filtering
  packages/api-headless-cms-ddb-es/__tests__/filtering/mocks/fields.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/mocks/plugins.ts
  packages/api-headless-cms-ddb-es/src/index.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/fields.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/applyFiltering.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/exec.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/isRefFieldFiltering.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/path.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/plugins/defaultFilterPlugin.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/plugins/index.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/plugins/objectFilterPlugin.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/plugins/refFilterPlugin.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/values.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/sort.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/types.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryFilterPlugin.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/createFilters.test.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/filter.test.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/createFilters.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/extractSort.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/filter.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/plugins/defaultFilterCreate.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/plugins/objectFilterCreate.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/plugins/refFilterCreate.ts
  packages/api-headless-cms-ddb/src/plugins/CmsEntryFieldFilterPlugin.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/filtering/product.nestedObject.test.ts
Labels: feature
