Repository webiny/webiny-js, pull requests merged in 2022-10, with the labels that each got.

#2648 feat(headless-cms): ability to delete locked field
  .eslintrc.js
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/lockedFields.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/multipleValues.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/richTextField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/helpers/filterModelFields.test.ts
  packages/api-headless-cms/__tests__/helpers/renderSortEnum.test.ts
  packages/api-headless-cms/__tests__/testHelpers/useProductManageHandler.ts
  packages/api-headless-cms/src/crud/contentModel/models.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
  packages/api-headless-cms/src/types.ts
  packages/api-headless-cms/src/utils/filterModelFields.ts
  packages/api-headless-cms/src/utils/renderSortEnum.ts
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
  packages/app-headless-cms/src/types.ts
Labels: feature

#2651 fix(api-headless-cms-ddb-es): date indexing
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/indexing/dateTimeIndexing.test.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/indexing/dateTimeIndexing.ts
  packages/api-headless-cms/src/utils/converters/valueKeyStorageConverter.ts
Labels: bug

#2654 feat(api-headless-cms): storage id validation
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/helpers/fields.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/plugins/CmsModelPlugin.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#2661 fix(api-apw): schedule publishing
  packages/api-apw/src/scheduler/handlers/executeAction/index.ts
  packages/api-headless-cms/src/utils/converters/valueKeyStorageConverter.ts
  packages/pulumi-aws/src/apps/api/ApiGraphql.ts
  packages/pulumi-aws/src/apps/api/createApiPulumiApp.ts
Labels: bug

#2666 fix(app-apw): change request body field overflow display
  packages/app-apw/package.json
  packages/app-apw/src/components/ContentReviewEditor/ChangeRequest/ChangeRequestDialog.tsx
  packages/app-apw/src/components/ContentReviewEditor/ChangeRequest/utils.tsx
  packages/app-apw/src/components/ContentReviewEditor/Comment/CommentBox.tsx
  packages/app-apw/src/hooks/useChangeRequest.ts
  packages/app-apw/src/hooks/useCmsEntries.ts
  packages/app-apw/src/hooks/useCmsModels.ts
  packages/app-apw/src/hooks/useComment.ts
  packages/app-apw/src/hooks/useCommentsList.ts
  packages/app-apw/src/hooks/useContentReview.ts
  packages/app-apw/src/hooks/usePbCategories.ts
  packages/app-apw/src/hooks/usePbPages.ts
  packages/app-apw/src/hooks/usePublishContent.ts
  packages/app-apw/src/hooks/usePublishingWorkflowForm.ts
  packages/app-apw/src/hooks/usePublishingWorkflowsList.ts
  packages/app-apw/src/hooks/useReviewers.ts
  packages/app-apw/src/hooks/useStepSignoff.ts
  packages/app-apw/src/plugins/cms/ApwOnEntryDelete.tsx
  packages/app-apw/src/plugins/cms/ApwOnEntryPublish.tsx
  packages/app-apw/src/plugins/cms/useContentReviewId.ts
  packages/app-apw/src/plugins/pageBuilder/ApwOnDelete.tsx
  packages/app-apw/src/plugins/pageBuilder/ApwOnPublish.tsx
  packages/app-apw/src/plugins/pageBuilder/useContentReviewId.ts
  packages/app-apw/src/views/publishingWorkflows/components/cms/ApwHeadlessCmsWorkflowScope.tsx
  packages/app-apw/src/views/publishingWorkflows/components/pageBuilder/ApwPageBuilderWorkflowScope.tsx
  yarn.lock
Labels: feature

#2664 Make FileManager composable
  apps/admin/src/App.fm.tsx
  packages/api-page-builder-import-export/src/exportPages/combine/index.ts
  packages/api-page-builder-import-export/src/exportPages/process/index.ts
  packages/api-page-builder-import-export/src/exportPages/s3Stream.ts
  packages/api-page-builder-import-export/src/graphql/crud/pages.crud.ts
  packages/api-page-builder-import-export/src/graphql/graphql/pages.gql.ts
  packages/api-page-builder-import-export/src/graphql/types.ts
  packages/api-page-builder-import-export/src/importPages/create/index.ts
  packages/api-page-builder-import-export/src/importPages/utils.ts
  packages/app-admin-users-cognito/src/ui/components/AvatarImage.tsx
  packages/app-admin/package.json
  packages/app-admin/src/components/FileManager.tsx
  packages/app-admin/src/components/FileManager/FileManagerView.tsx
  packages/app-admin/src/components/FileManager/outputFileSelectionError.ts
  packages/app-admin/src/components/FileManager/types.ts
  packages/app-admin/src/components/OverlayLayout/OverlayLayout.tsx
  packages/app-admin/src/components/OverlayLayout/index.ts
  packages/app-admin/src/components/RichTextEditor/RichTextEditor.tsx
  packages/app-admin/src/components/SingleImageUpload.tsx
  packages/app-admin/src/index.ts
  packages/app-admin/src/plugins/fileManager/fileImage/DeleteAction.tsx
  packages/app-admin/src/plugins/fileManager/fileImage/EditAction.tsx
  packages/app-admin/src/ui/elements/form/FileManagerElement/FileManagerElementRenderer.tsx
  packages/app-admin/tsconfig.build.json
  packages/app-admin/tsconfig.json
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileField.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileFields.tsx
  packages/app-page-builder/src/admin/graphql/pageImportExport.gql.ts
  packages/app-page-builder/src/admin/views/Pages/hooks/useImportPage.ts
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ExportPageButton/useExportPageDialog.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ImportPageButton/index.tsx
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ImportPageButton/useImportPageDialog.tsx
  packages/app-page-builder/src/editor/plugins/elements/image/ImageContainer.tsx
  packages/app-page-builder/src/editor/plugins/elements/imagesList/File.tsx
  packages/app-page-builder/src/editor/plugins/elements/imagesList/ImagesListImagesSettings.tsx
  packages/app-page-builder/src/editor/plugins/elements/imagesList/index.tsx
  packages/app-page-builder/src/editor/ui/views/GeneralSettingsView.ts
  packages/app-page-builder/src/editor/ui/views/SocialSettingsView.ts
  packages/app-page-builder/src/modules/WebsiteSettings/settingsGroups/FaviconAndLogo.tsx
  packages/app-page-builder/src/modules/WebsiteSettings/settingsGroups/SocialMedia.tsx
  packages/app-tenancy/src/Tenancy.tsx
  packages/pulumi-aws/src/apps/common/VpcConfig.ts
  packages/pulumi-aws/src/apps/lambdaUtils.ts
  packages/react-composition/src/Context.tsx
  packages/react-composition/tsconfig.json
  yarn.lock
Labels: feature, umbrella ☂️

#2679 feat(api-headless-cms): upgrade for all tenants
  packages/api-headless-cms/__tests__/upgrades/upgrade.5330.test.ts
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/upgrades/5.33.0/index.ts
  packages/api-i18n-ddb/src/operations/locales/LocalesStorageOperations.ts
  packages/api-i18n/src/graphql/crud/locales.crud.ts
  packages/api-i18n/src/graphql/crud/system.crud.ts
  packages/api-i18n/src/types.ts
Labels: bug, api

#2676 fix: folders-api update operation
  packages/api-folders-so-ddb/package.json
  packages/api-folders-so-ddb/src/operations/folders.ts
  packages/api-folders-so-ddb/src/operations/links.ts
  packages/api-folders/__tests__/folders.test.ts
  packages/api-folders/package.json
  packages/api-folders/src/context/folders.ts
  packages/api-folders/src/context/links.ts
  packages/api-folders/src/types.ts
  yarn.lock
Labels: bug

#2681 feat(api-page-builder): remove default workflows
  packages/api-apw/__tests__/utils/graphql/pages.ts
  packages/api-apw/src/types.ts
  packages/api-page-builder-so-ddb-es/src/operations/pages/index.ts
  packages/api-page-builder-so-ddb/src/operations/pages/index.ts
  packages/api-page-builder/__tests__/graphql/graphql/pages.ts
  packages/api-page-builder/__tests__/graphql/lifecycleEvents.pages.test.ts
  packages/api-page-builder/__tests__/graphql/listPageTags.test.ts
  packages/api-page-builder/__tests__/graphql/mocks/index.ts
  packages/api-page-builder/__tests__/graphql/mocks/lifecycleEvents.ts
  packages/api-page-builder/__tests__/graphql/pagesListingLatest.test.ts
  packages/api-page-builder/__tests__/graphql/publishingWorkflow.test.ts
  packages/api-page-builder/__tests__/graphql/simple.pages.test.ts
  packages/api-page-builder/__tests__/graphql/useGqlHandler.ts
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/graphql/pages.gql.ts
  packages/api-page-builder/src/graphql/types.ts
  packages/api-page-builder/src/types.ts
Labels: feature

#2686 feat(api-apw): security permissions
  packages/api-apw/__tests__/graphql/workflow.crud.test.ts
  packages/api-apw/__tests__/utils/createPageBuilderGQLHandler.ts
  packages/api-apw/__tests__/utils/helpers.ts
  packages/api-apw/__tests__/utils/usePageBuilderHandler.ts
  packages/api-apw/src/crud/createWorkflowMethods.ts
Labels: feature

#2691 feat(api-apw): only list current users content reviews
  packages/api-apw/src/crud/createWorkflowMethods.ts
  packages/api-apw/src/plugins/cms/utils.ts
  packages/api-apw/src/plugins/hooks/index.ts
  packages/api-apw/src/plugins/hooks/initializeContentReviewSteps.ts
  packages/api-apw/src/plugins/hooks/listContentReviews.ts
  packages/api-apw/src/plugins/pageBuilder/linkContentReviewToPage.ts
  packages/api-apw/src/plugins/pageBuilder/linkWorkflowToPage.ts
  packages/api-apw/src/storageOperations/index.ts
  packages/api-apw/src/storageOperations/models/contentReview.model.ts
  packages/api-apw/src/types.ts
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-page-builder/src/types.ts
Labels: feature

#2733 feat(api-mailer): add security permissions and checks
  packages/api-mailer/__tests__/context/helpers.ts
  packages/api-mailer/__tests__/settings.crud.test.ts
  packages/api-mailer/__tests__/settings.graphql.test.ts
  packages/api-mailer/src/crud/settings.crud.ts
  packages/app-mailer/src/plugins/Module.tsx
  packages/cwp-template-aws/template/common/types/env/index.d.ts
  typings/env/index.d.ts
Labels: improvement

#2640 feat: add folder tree component
  packages/api-folders-so-ddb/package.json
  packages/api-folders-so-ddb/src/operations/folders.ts
  packages/api-folders/package.json
  packages/api-folders/src/graphql/folders.gql.ts
  packages/app-folders/.babelrc.js
  packages/app-folders/LICENSE
  packages/app-folders/README.md
  packages/app-folders/package.json
  packages/app-folders/src/components/Tree/ButtonCreate/index.tsx
  packages/app-folders/src/components/Tree/ButtonCreate/styled.tsx
  packages/app-folders/src/components/Tree/DialogCreate/index.tsx
  packages/app-folders/src/components/Tree/DialogCreate/styled.tsx
  packages/app-folders/src/components/Tree/Node/index.tsx
  packages/app-folders/src/components/Tree/Node/styled.tsx
  packages/app-folders/src/components/Tree/NodePreview/index.tsx
  packages/app-folders/src/components/Tree/NodePreview/styled.tsx
  packages/app-folders/src/components/Tree/Title/index.tsx
  packages/app-folders/src/components/Tree/Title/styled.tsx
  packages/app-folders/src/components/Tree/index.tsx
  packages/app-folders/src/components/Tree/styled.tsx
  packages/app-folders/src/contexts/folders.tsx
  packages/app-folders/src/contexts/index.tsx
  packages/app-folders/src/contexts/links.tsx
  packages/app-folders/src/graphql/folders.gql.ts
  packages/app-folders/src/graphql/links.gql.ts
  packages/app-folders/src/handlers.tsx
  packages/app-folders/src/hooks/index.ts
  packages/app-folders/src/hooks/useFolders.ts
  packages/app-folders/src/hooks/useLinks.ts
  packages/app-folders/src/index.ts
  packages/app-folders/src/types.ts
  packages/app-folders/tsconfig.build.json
  packages/app-folders/tsconfig.json
  packages/app-folders/webiny.config.js
  packages/app-page-builder/src/editor/plugins/toolbar/navigator/navigatorHooks.ts
  yarn.lock
Labels: page-builder
