Repository webiny/webiny-js, pull requests merged in 2022-11, with the labels that each got.

#2692 feat: DataTable UI component
  apps/admin/src/App.scss
  packages/app-admin/src/styles/material-theme-assignments.scss
  packages/app-admin/src/styles/material.scss
  packages/app-admin/src/styles/theme.scss
  packages/ui/package.json
  packages/ui/src/DataTable/DataTable.stories.tsx
  packages/ui/src/DataTable/DataTable.tsx
  packages/ui/src/DataTable/README.md
  packages/ui/src/DataTable/index.ts
  packages/ui/src/DataTable/styled.tsx
  packages/ui/src/styles.scss
  yarn.lock
Labels: feature

#2765 fix(handler-graphql): number scalar
  packages/api-headless-cms/src/graphql/schema/baseContentSchema.ts
  packages/handler-graphql/__tests__/NumberScalar.test.ts
  packages/handler-graphql/src/builtInTypes/AnyScalar.ts
  packages/handler-graphql/src/builtInTypes/NumberScalar.ts
  packages/handler-graphql/src/createGraphQLSchema.ts
Labels: bug

#2759 feat(DataTable): add row selection feature
  packages/ui/src/DataTable/DataTable.stories.tsx
  packages/ui/src/DataTable/DataTable.tsx
  packages/ui/src/DataTable/styled.tsx
Labels: feature

#2779 fix(api-headless-cms-ddb-es): body modifier
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/index.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchBodyModifierPlugin.ts
  packages/api-headless-cms-ddb-es/src/types.ts
Labels: bug

#2802 feat(api-elasticsearch): optimize operators
  packages/api-elasticsearch/__tests__/plugins/operators/between.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/contains.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/equal.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/gt.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/gte.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/in.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/lt.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/lte.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/not.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/notBetween.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/notContains.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/notIn.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/notStartsWith.test.ts
  packages/api-elasticsearch/__tests__/plugins/operators/startsWith.test.ts
  packages/api-elasticsearch/__tests__/search/japanese.test.ts
  packages/api-elasticsearch/__tests__/where.test.ts
  packages/api-elasticsearch/src/cursors.ts
  packages/api-elasticsearch/src/normalize.ts
  packages/api-elasticsearch/src/plugins/operator/andIn.ts
  packages/api-elasticsearch/src/plugins/operator/between.ts
  packages/api-elasticsearch/src/plugins/operator/equal.ts
  packages/api-elasticsearch/src/plugins/operator/gt.ts
  packages/api-elasticsearch/src/plugins/operator/gte.ts
  packages/api-elasticsearch/src/plugins/operator/in.ts
  packages/api-elasticsearch/src/plugins/operator/lt.ts
  packages/api-elasticsearch/src/plugins/operator/lte.ts
  packages/api-elasticsearch/src/plugins/operator/not.ts
  packages/api-elasticsearch/src/plugins/operator/notBetween.ts
  packages/api-elasticsearch/src/plugins/operator/notIn.ts
  packages/api-elasticsearch/src/plugins/operator/startsWith.ts
  packages/api-elasticsearch/src/sort.ts
  packages/api-elasticsearch/src/types.ts
  packages/api-elasticsearch/src/where.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
Labels: feature

#2811 feat: add folder item actions menu
  packages/app-folders/src/components/Dialogs/DialogCreate.tsx
  packages/app-folders/src/components/Dialogs/DialogDelete.tsx
  packages/app-folders/src/components/Dialogs/DialogUpdate.tsx
  packages/app-folders/src/components/Dialogs/index.tsx
  packages/app-folders/src/components/Dialogs/styled.tsx
  packages/app-folders/src/components/Tree/MenuActions/index.tsx
  packages/app-folders/src/components/Tree/MenuActions/styled.tsx
  packages/app-folders/src/components/Tree/Node/index.tsx
  packages/app-folders/src/components/Tree/Node/styled.tsx
  packages/app-folders/src/components/Tree/index.tsx
  packages/app-page-builder/src/admin/components/Table/Row/Folder/FolderActionDelete.tsx
  packages/app-page-builder/src/admin/components/Table/Table.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
Labels: feature, page-builder
