Repository webiny/webiny-js, pull requests merged in 2022-09, with the labels that each got.

#2593 fix(api-apw): fine grained permissions
  packages/api-apw/__tests__/graphql/access.test.ts
  packages/api-apw/__tests__/graphql/mocks/access/permissions.ts
  packages/api-apw/__tests__/graphql/mocks/access/plugins.ts
  packages/api-apw/__tests__/utils/helpers.ts
  packages/api-apw/__tests__/utils/useAdminHeadlessCmsHandler.ts
  packages/api-apw/src/plugins/context.ts
  packages/api-apw/src/plugins/hooks/validateComment.ts
  packages/api-apw/src/storageOperations/changeRequestStorageOperations.ts
  packages/api-apw/src/storageOperations/commentStorageOperations.ts
  packages/api-apw/src/storageOperations/contentReviewStorageOperations.ts
  packages/api-apw/src/storageOperations/index.ts
  packages/api-apw/src/storageOperations/models/contentModelPluginFactory.ts
  packages/api-apw/src/storageOperations/models/index.ts
  packages/api-apw/src/storageOperations/reviewerStorageOperations.ts
  packages/api-apw/src/storageOperations/workflowStorageOperations.ts
  packages/api-headless-cms/src/plugins/CmsGroupPlugin.ts
  packages/api-headless-cms/src/plugins/CmsModelPlugin.ts
Labels: bug

#2613 feat(app-headless-cms): make fieldId changeable
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/contentAPI/lockedFields.test.ts
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/crud/contentModel/beforeCreate.ts
  packages/api-headless-cms/src/crud/contentModel/beforeUpdate.ts
  packages/api-headless-cms/src/crud/contentModel/validateLayout.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
  packages/app-headless-cms/package.json
  packages/app-headless-cms/src/admin/components/FieldEditor/EditFieldDialog.tsx
  packages/app-headless-cms/src/admin/components/FieldEditor/EditFieldDialog/GeneralTab.tsx
  packages/app-headless-cms/src/admin/components/FieldEditor/FieldEditorContext.tsx
  packages/app-headless-cms/src/admin/graphql/contentModels.ts
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/object/multipleObjects.tsx
  packages/app-headless-cms/src/admin/views/contentEntries/experiment/Property.tsx
  packages/utils/src/generateId.ts
  yarn.lock
Labels: feature

#2592 feat: folder CRUD module
  packages/api-folders-so-ddb/.babelrc.js
  packages/api-folders-so-ddb/LICENSE
  packages/api-folders-so-ddb/README.md
  packages/api-folders-so-ddb/__tests__/__api__/environment.js
  packages/api-folders-so-ddb/__tests__/__api__/presets.js
  packages/api-folders-so-ddb/__tests__/__api__/setupAfterEnv.js
  packages/api-folders-so-ddb/jest-dynalite-config.js
  packages/api-folders-so-ddb/jest.config.js
  packages/api-folders-so-ddb/package.json
  packages/api-folders-so-ddb/src/definitions/entities.ts
  packages/api-folders-so-ddb/src/definitions/table.ts
  packages/api-folders-so-ddb/src/index.ts
  packages/api-folders-so-ddb/src/operations/folders.ts
  packages/api-folders-so-ddb/src/operations/links.ts
  packages/api-folders-so-ddb/src/types.ts
  packages/api-folders-so-ddb/tsconfig.build.json
  packages/api-folders-so-ddb/tsconfig.json
  packages/api-folders-so-ddb/webiny.config.js
  packages/api-folders/.babelrc.js
  packages/api-folders/LICENSE
  packages/api-folders/README.md
  packages/api-folders/__tests__/folders.test.ts
  packages/api-folders/__tests__/graphql/folders.ts
  packages/api-folders/__tests__/graphql/links.ts
  packages/api-folders/__tests__/links.test.ts
  packages/api-folders/__tests__/mocks/folders.ts
  packages/api-folders/__tests__/mocks/links.ts
  packages/api-folders/__tests__/tenancySecurity.ts
  packages/api-folders/__tests__/useGqlHandler.ts
  packages/api-folders/jest.setup.js
  packages/api-folders/package.json
  packages/api-folders/src/context/folders.ts
  packages/api-folders/src/context/index.ts
  packages/api-folders/src/context/links.ts
  packages/api-folders/src/graphql/base.gql.ts
  packages/api-folders/src/graphql/folders.gql.ts
  packages/api-folders/src/graphql/index.ts
  packages/api-folders/src/graphql/links.gql.ts
  packages/api-folders/src/index.ts
  packages/api-folders/src/types.ts
  packages/api-folders/tsconfig.build.json
  packages/api-folders/tsconfig.json
  packages/api-folders/webiny.config.js
  yarn.lock
Labels: api

#2614 feat(api-headless-cms): entry values path conversion
  packages/api-headless-cms-ddb-es/src/operations/model/index.ts
  packages/api-headless-cms-ddb/src/operations/model/index.ts
  packages/api-headless-cms/__tests__/contentAPI/fieldIdStorageConverter.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/fieldIdStorageConverter.ts
  packages/api-headless-cms/package.json
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/crud/contentModel/beforeDelete.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/fieldConverters/CmsModelDefaultFieldConverterPlugin.ts
  packages/api-headless-cms/src/fieldConverters/CmsModelObjectFieldConverterPlugin.ts
  packages/api-headless-cms/src/fieldConverters/index.ts
  packages/api-headless-cms/src/index.ts
  packages/api-headless-cms/src/plugins/CmsModelFieldConverterPlugin.ts
  packages/api-headless-cms/src/plugins/index.ts
  packages/api-headless-cms/src/types.ts
  packages/api-headless-cms/src/utils/converters/Converter.ts
  packages/api-headless-cms/src/utils/converters/ConverterCollection.ts
  packages/api-headless-cms/src/utils/converters/valueKeyStorageConverter.ts
  yarn.lock
Labels: feature

#2620 feat(api-headless-cms-ddb): implement conversion of field paths
  packages/api-apw/__tests__/graphql/workflowHooks.crud.test.ts
  packages/api-headless-cms-ddb/src/operations/entry/index.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntryMetaField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/entryPaginatipon.test.ts
  packages/api-headless-cms/__tests__/contentAPI/fieldIdStorageConverter.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/fieldIdStorageConverter.ts
  packages/api-headless-cms/__tests__/contentAPI/republish.entries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.read.test.ts
  packages/api-headless-cms/__tests__/storageOperations/entries.test.ts
  packages/api-headless-cms/__tests__/storageOperations/helpers.ts
  packages/api-headless-cms/__tests__/utils/useGraphQLHandler.ts
  packages/api-headless-cms/src/fieldConverters/CmsModelDefaultFieldConverterPlugin.ts
  packages/api-headless-cms/src/fieldConverters/CmsModelObjectFieldConverterPlugin.ts
  packages/api-headless-cms/src/utils/converters/ConverterCollection.ts
  packages/api-headless-cms/src/utils/converters/valueKeyStorageConverter.ts
Labels: feature

#2622 feat(api-headless-cms-ddb-es): transformation of fieldId and storageId paths
  packages/api-elasticsearch/src/plugins/definition/ElasticsearchFieldPlugin.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/elasticsearch/indexing/objectIndexing.test.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/date.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/indexing/objectIndexing.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/search/refSearch.ts
  packages/api-headless-cms-ddb-es/src/helpers/createElasticsearchQueryBody.ts
  packages/api-headless-cms-ddb-es/src/helpers/entryIndexHelpers.ts
  packages/api-headless-cms-ddb-es/src/helpers/fields.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/fields.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntryMetaField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.noValidation.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/storageOperations/helpers.ts
Labels: feature

#2632 feat(api-headless-cms): model fields upgrade
  packages/api-headless-cms/__tests__/upgrades/upgrade.5330.test.ts
  packages/api-headless-cms/__tests__/utils/graphql/settings.ts
  packages/api-headless-cms/__tests__/utils/useGraphQLHandler.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
  packages/api-headless-cms/src/upgrades/5.33.0/index.ts
  packages/api-headless-cms/src/upgrades/index.ts
Labels: feature

#2641 fix(api-headless-cms): field storage plugins
  packages/api-headless-cms-ddb-es/__tests__/plugins/dynamoDb/storage/longText.test.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/dynamoDb/storage/plugins.ts
  packages/api-headless-cms-ddb-es/__tests__/plugins/dynamoDb/storage/richText.test.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/index.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/longText.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/richText.ts
  packages/api-headless-cms-ddb/__tests__/plugins/dynamoDb/storage/longText.test.ts
  packages/api-headless-cms-ddb/__tests__/plugins/dynamoDb/storage/plugins.ts
  packages/api-headless-cms-ddb/__tests__/plugins/dynamoDb/storage/richText.test.ts
  packages/api-headless-cms-ddb/src/dynamoDb/storage/longText.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/multipleValues.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/richTextField.test.ts
  packages/api-headless-cms/__tests__/converters/fieldIdStorageConverter.test.ts
  packages/api-headless-cms/__tests__/converters/mocks/fieldIdStorageConverter.ts
  packages/api-headless-cms/__tests__/plugins/storage/container.ts
  packages/api-headless-cms/__tests__/plugins/storage/object.test.ts
  packages/api-headless-cms/__tests__/plugins/storage/object/model.ts
  packages/api-headless-cms/__tests__/utils/useProductManageHandler.ts
  packages/api-headless-cms/__tests__/utils/useProductReadHandler.ts
  packages/api-headless-cms/src/fieldConverters/CmsModelObjectFieldConverterPlugin.ts
  packages/api-headless-cms/src/storage/object.ts
  packages/app-headless-cms/src/admin/components/ContentEntryForm/useContentEntryForm.ts
  packages/app-headless-cms/src/admin/views/contentEntries/ContentEntry/prepareFormData.ts
Labels: bug

#2642 fix(api-headless-cms): long text field decompression
  packages/api-headless-cms-ddb-es/__tests__/plugins/dynamoDb/storage/longText.test.ts
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/longText.ts
  packages/api-headless-cms-ddb/__tests__/plugins/dynamoDb/storage/longText.test.ts
  packages/api-headless-cms-ddb/src/dynamoDb/storage/longText.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.read.ts
  packages/api-headless-cms/__tests__/utils/useProductManageHandler.ts
Labels: bug
