Repository webiny/webiny-js, pull requests merged in 2023-06, with the labels that each got.

#3355 fix: page builder url with no website deployed
  packages/app-page-builder/src/admin/hooks/usePageBuilderSettings/usePageBuilderSettings.ts
Labels: page-builder

#3304 feat(lexical): toolbar text alignment actions
  packages/app-page-builder/src/editor/plugins/elementSettings/text/TextSettings.tsx
  packages/lexical-editor-actions/src/LexicalEditorActions.tsx
  packages/lexical-editor-actions/src/components/TextAlignmentDropdown.tsx
  packages/lexical-editor/src/components/LexicalEditorConfig/LexicalEditorConfig.tsx
  packages/lexical-editor/src/components/Toolbar/Toolbar.css
  packages/lexical-editor/src/components/Toolbar/Toolbar.tsx
  packages/lexical-editor/src/components/ToolbarActions/QuoteAction.tsx
  packages/lexical-editor/src/components/ToolbarActions/TextAlignmentAction.tsx
  packages/lexical-editor/src/components/ToolbarPresets/HeadingToolbarPreset.tsx
  packages/lexical-editor/src/components/ToolbarPresets/ParagraphToolbarPreset.tsx
  packages/lexical-editor/src/context/RichTextEditorContext.tsx
  packages/lexical-editor/src/context/TextAlignmentActionContextProps.tsx
  packages/lexical-editor/src/hooks/useTextAlignmentAction.ts
  packages/lexical-editor/src/images/icons/indent.svg
  packages/lexical-editor/src/images/icons/justify.svg
  packages/lexical-editor/src/images/icons/outdent.svg
  packages/lexical-editor/src/index.tsx
  packages/lexical-editor/src/types.ts
  packages/lexical-editor/src/utils/getLexicalTextSelectionState.ts
Labels: page-builder

#3184 feat: add tabs element
  apps/admin/src/plugins/pageBuilder/editorPlugins.ts
  apps/admin/src/plugins/pageBuilder/renderPlugins.ts
  apps/website/src/plugins/pageBuilder.ts
  packages/app-page-builder-elements/src/renderers/tab.tsx
  packages/app-page-builder-elements/src/renderers/tabs.tsx
  packages/app-page-builder/src/editor/contexts/EditorPageElementsProvider/ElementControls.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/tab/TabSettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/tab/index.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/tabs/TabsList.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/tabs/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/tab/PeTab.tsx
  packages/app-page-builder/src/editor/plugins/elements/tab/Tab.tsx
  packages/app-page-builder/src/editor/plugins/elements/tab/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/tabs/PeTabs.tsx
  packages/app-page-builder/src/editor/plugins/elements/tabs/Tabs.tsx
  packages/app-page-builder/src/editor/plugins/elements/tabs/index.tsx
  packages/app-page-builder/src/render/plugins/elements/tab/index.tsx
  packages/app-page-builder/src/render/plugins/elements/tabs/index.tsx
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/pageBuilder/editorPlugins.ts
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/pageBuilder/renderPlugins.ts
  packages/cwp-template-aws/template/common/apps/website/src/plugins/pageBuilder.ts
Labels: needs-migration

#3145 feat: add cell mirroring option
  apps/admin/src/plugins/pageBuilder/editorPlugins.ts
  packages/app-page-builder/src/editor/assets/icons/mirror_cell.svg
  packages/app-page-builder/src/editor/config/ActionPlugins.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/index.ts
  packages/app-page-builder/src/editor/plugins/elementSettings/mirror-cell/MirrorCellAction.ts
  packages/app-page-builder/src/editor/plugins/elementSettings/mirror-cell/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/cell/index.tsx
  packages/app-page-builder/src/editor/recoil/actions/mirrorCell/action.ts
  packages/app-page-builder/src/editor/recoil/actions/mirrorCell/event.ts
  packages/app-page-builder/src/editor/recoil/actions/mirrorCell/index.ts
  packages/app-page-builder/src/editor/recoil/actions/mirrorCell/plugin.ts
  packages/app-page-builder/src/editor/recoil/actions/mirrorCell/types.ts
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/pageBuilder/editorPlugins.ts
Labels: needs-migration

#3276 feat: add carousel element
  apps/admin/src/plugins/pageBuilder/editorPlugins.ts
  apps/admin/src/plugins/pageBuilder/renderPlugins.ts
  apps/website/src/plugins/pageBuilder.ts
  packages/app-page-builder-elements/package.json
  packages/app-page-builder-elements/src/renderers/carousel.tsx
  packages/app-page-builder-elements/src/renderers/carouselElement.tsx
  packages/app-page-builder/package.json
  packages/app-page-builder/src/editor/plugins/elementSettings/carousel/Carousel.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/carousel/index.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/carouselElement/CarouselElementSettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/carouselElement/index.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/carouselStyles/CarouselStyles.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/carouselStyles/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/carousel/Carousel.tsx
  packages/app-page-builder/src/editor/plugins/elements/carousel/PeCarousel.tsx
  packages/app-page-builder/src/editor/plugins/elements/carousel/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/carouselElement/CarouselElement.tsx
  packages/app-page-builder/src/editor/plugins/elements/carouselElement/PeCarouselElement.tsx
  packages/app-page-builder/src/editor/plugins/elements/carouselElement/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/grid/index.tsx
  packages/app-page-builder/src/render/plugins/elements/carousel/index.tsx
  packages/app-page-builder/src/render/plugins/elements/carouselElement/index.tsx
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/pageBuilder/editorPlugins.ts
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/pageBuilder/renderPlugins.ts
  packages/cwp-template-aws/template/common/apps/website/src/plugins/pageBuilder.ts
  yarn.lock
Labels: needs-migration

#3125 feat: add Google Analytics Event trigger
  apps/admin/src/plugins/formBuilder.ts
  apps/website/src/plugins/formBuilder.ts
  packages/app-form-builder/package.json
  packages/app-form-builder/src/admin/plugins/editor/triggers/components/GoogleAnalyticsEventDynamicFieldset.tsx
  packages/app-form-builder/src/admin/plugins/editor/triggers/googleAnalyticsEvent.tsx
  packages/app-form-builder/src/render/plugins/triggers/googleAnalyticsEvent.ts
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/formBuilder.ts
  packages/cwp-template-aws/template/common/apps/website/src/plugins/formBuilder.ts
  yarn.lock
Labels: needs-migration

#3371 refactor(migrations): change default root folder to lowercase migration
  packages/api-elasticsearch/src/plugins/GzipCompression.ts
  packages/migrations/__tests__/migrations/5.36.0/001/ddb-es/001.test.ts
  packages/migrations/__tests__/migrations/5.36.0/001/ddb/001.test.ts
  packages/migrations/__tests__/migrations/5.37.0/001/ddb-es/001.test.ts
  packages/migrations/__tests__/migrations/5.37.0/002/common/createdBy.ts
  packages/migrations/__tests__/migrations/5.37.0/002/common/index.ts
  packages/migrations/__tests__/migrations/5.37.0/002/common/locales.ts
  packages/migrations/__tests__/migrations/5.37.0/002/common/tenants.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb-es/002.test.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb-es/data.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb-es/getDecompressedData.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb-es/insertTestFolders.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb/002.test.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb/data.ts
  packages/migrations/__tests__/migrations/5.37.0/002/ddb/insertTestFolders.ts
  packages/migrations/__tests__/migrations/5.37.0/002/types.ts
  packages/migrations/__tests__/utils/insertElasticsearchTestData.ts
  packages/migrations/src/ddb-es.ts
  packages/migrations/src/ddb.ts
  packages/migrations/src/migrations/5.37.0/001/constants.ts
  packages/migrations/src/migrations/5.37.0/001/ddb-es/PageDataMigration.ts
  packages/migrations/src/migrations/5.37.0/001/ddb/PageDataMigration.ts
  packages/migrations/src/migrations/5.37.0/002/constants.ts
  packages/migrations/src/migrations/5.37.0/002/ddb-es/AcoFolderMigration.ts
  packages/migrations/src/migrations/5.37.0/002/ddb-es/index.ts
  packages/migrations/src/migrations/5.37.0/002/ddb-es/latestElasticsearchData.ts
  packages/migrations/src/migrations/5.37.0/002/ddb/AcoFolderMigration.ts
  packages/migrations/src/migrations/5.37.0/002/ddb/index.ts
  packages/migrations/src/migrations/5.37.0/002/entities/createEntryEntity.ts
  packages/migrations/src/migrations/5.37.0/002/entities/createLocaleEntity.ts
  packages/migrations/src/migrations/5.37.0/002/entities/createTenantEntity.ts
  packages/migrations/src/migrations/5.37.0/002/types.ts
  packages/migrations/src/migrations/5.37.0/002/utils/getCompressedData.ts
Labels: aco

#3209 feat: add a date and time fields as field options
  apps/admin/src/plugins/formBuilder.ts
  apps/theme/layouts/forms/DefaultFormLayout/Field.tsx
  apps/theme/layouts/forms/DefaultFormLayout/fields/Date.tsx
  apps/theme/layouts/forms/DefaultFormLayout/fields/Select.tsx
  apps/theme/package.json
  packages/api-form-builder/src/plugins/validators/dateGte.ts
  packages/api-form-builder/src/plugins/validators/dateLte.ts
  packages/api-form-builder/src/plugins/validators/index.ts
  packages/app-form-builder/package.json
  packages/app-form-builder/src/admin/components/FormEditor/Tabs/EditTab/EditFieldDialog/ValidatorsTab.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFieldValidators/dateGte.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFieldValidators/dateLte.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFields/components/DateTime.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFields/dateTime.tsx
  packages/app-form-builder/src/render/plugins/validators/dateGte.ts
  packages/app-form-builder/src/render/plugins/validators/dateLte.ts
  packages/app-form-builder/src/types.ts
  packages/app-form-builder/tsconfig.build.json
  packages/app-form-builder/tsconfig.json
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/DateTimeWithTimezone.tsx
  packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/utils.tsx
  packages/utils/src/index.ts
  packages/utils/src/utcTimezones.ts
  yarn.lock
Labels: needs-migration

#3380 fix(app-aco): fetch only simple fields when listing entries
  packages/app-aco/src/graphql/records/listRecords.ts
Labels: bug, cms

#3359 feat(Lexical): Rich Text Lexical Renderer Component
  packages/lexical-editor/src/types.ts
  packages/react-rich-text-lexical-renderer/.babelrc.js
  packages/react-rich-text-lexical-renderer/LICENSE
  packages/react-rich-text-lexical-renderer/README.md
  packages/react-rich-text-lexical-renderer/__tests__/lexical-content.ts
  packages/react-rich-text-lexical-renderer/__tests__/lexical-render.ts
  packages/react-rich-text-lexical-renderer/__tests__/lexical-renderer.test.tsx
  packages/react-rich-text-lexical-renderer/jest.config.js
  packages/react-rich-text-lexical-renderer/package.json
  packages/react-rich-text-lexical-renderer/src/index.tsx
  packages/react-rich-text-lexical-renderer/tsconfig.build.json
  packages/react-rich-text-lexical-renderer/tsconfig.json
  packages/react-rich-text-lexical-renderer/webiny.config.js
  yarn.lock
Labels: lexical-editor

#3392 fix(app-apw): dialog to initialize content review
  packages/app-admin-rmwc/src/modules/Overlays/Dialog.tsx
  packages/app-admin/src/hooks/useConfirmationDialog.tsx
  packages/app-apw/src/plugins/cms/ApwOnEntryPublish.tsx
Labels: cms

#3393 test(migrations): reduce amount of test records
  packages/migrations/__tests__/migrations/5.35.0/001/ddb-es/001.test.ts
  packages/migrations/__tests__/migrations/5.35.0/001/ddb/001.test.ts
  packages/migrations/__tests__/migrations/5.35.0/006/ddb-es/insertTestPages.ts
  packages/migrations/__tests__/migrations/5.35.0/006/ddb/insertTestPages.ts
  packages/migrations/__tests__/migrations/5.36.0/001/ddb-es/001.test.ts
  packages/migrations/__tests__/migrations/5.36.0/001/ddb/001.test.ts
Labels: api
