Repository webiny/webiny-js, pull requests merged in 2023-01, with the labels that each got.

#2911 Fix Import Paths in `loadEnvironmentVariables.js`
  packages/cli/context.js
  packages/cli/utils/loadEnvVariables.js
Labels: bug

#2910 fix: folder initial open list
  packages/app-folders/src/components/Tree/List/index.tsx
Labels: page-builder

#2914 feat: enable ACO for page-builder
  cypress/integration/admin/pageBuilder/page/createPage.spec.js
  cypress/integration/admin/pageBuilder/page/previewPage.spec.js
  cypress/integration/admin/pageBuilder/page/publishPage.spec.js
  packages/app-page-builder/src/admin/components/Table/Row/Name.tsx
  packages/app-page-builder/src/admin/plugins/routes.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Sidebar.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/index.tsx
  packages/app-page-builder/src/hooks/usePageViewNavigation.tsx
  packages/app-page-builder/src/pageEditor/config/editorBar/BackButton/BackButton.tsx
  packages/app-page-builder/src/pageEditor/config/editorBar/PageOptionsMenu/SetAsHomepageButton.tsx
  packages/app-page-builder/src/pageEditor/config/editorBar/PublishPageButton/PublishPageButton.tsx
  packages/app-page-builder/src/pageEditor/config/editorBar/SetAsHomepageButton/SetAsHomepageButton.tsx
Labels: page-builder

#2886 feat: 5.34.0 upgrade script for PageBuilder
  packages/api-page-builder/__tests__/folders.ts
  packages/api-page-builder/__tests__/graphql/useGqlHandler.ts
  packages/api-page-builder/package.json
  packages/api-page-builder/src/graphql/crud/system.crud.ts
  packages/api-page-builder/src/graphql/index.ts
  packages/api-page-builder/src/graphql/subscriptions/afterSystemInstall.ts
  packages/api-page-builder/src/graphql/subscriptions/index.ts
  packages/api-page-builder/src/graphql/types.ts
  packages/api-page-builder/src/graphql/upgrades/index.ts
  packages/api-page-builder/src/graphql/upgrades/v5.34.0/index.ts
  packages/api-page-builder/tsconfig.build.json
  packages/api-page-builder/tsconfig.json
  packages/app-page-builder/src/admin/plugins/installation.tsx
  packages/app-page-builder/src/admin/plugins/upgrades/v5.34.0.tsx
  yarn.lock
Labels: page-builder

#2908 fix: various DataTable list
  packages/app-page-builder/src/admin/components/Table/Empty/index.tsx
  packages/app-page-builder/src/admin/components/Table/Empty/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Header.tsx
  packages/app-page-builder/src/admin/components/Table/Header/ButtonsCreate/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/ButtonsCreate/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Header/Title/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/Title/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Header/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/styled.tsx
  packages/app-page-builder/src/admin/components/Table/LoadingMore.tsx
  packages/app-page-builder/src/admin/components/Table/LoadingMore/index.tsx
  packages/app-page-builder/src/admin/components/Table/LoadingMore/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Preview/index.tsx
  packages/app-page-builder/src/admin/components/Table/Preview/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Folder/FolderActionDelete.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Folder/FolderActionEdit.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Name.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Page/PageActionDelete.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Page/PageActionEdit.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Page/PageActionPreview.tsx
  packages/app-page-builder/src/admin/components/Table/Table/Row/Page/PageActionPublish.tsx
  packages/app-page-builder/src/admin/components/Table/Table/index.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/pageRevisions/RevisionsList.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/previewContent/PagePreview.tsx
  packages/app-page-builder/src/admin/views/Pages/PageDetails.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Sidebar.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/index.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/styled.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useGetPages.ts
  packages/ui/src/DataTable/DataTable.tsx
  packages/ui/src/DataTable/styled.tsx
  packages/ui/src/Typography/Typography.tsx
Labels: page-builder

#2920 feat: add "load more" button
  packages/app-page-builder/src/admin/components/Table/LoadMoreButton/LoadMoreButton.tsx
  packages/app-page-builder/src/admin/components/Table/LoadMoreButton/index.ts
  packages/app-page-builder/src/admin/components/Table/LoadMoreButton/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Table/index.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
Labels: page-builder

#2916 feat(api-headless-cms-ddb): conditional filtering
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/assignMinimumShouldMatchToQuery.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/body.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/filtering/exec.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/createExpressions.test.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/createFields.test.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/createFilters.test.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/filter.test.ts
  packages/api-headless-cms-ddb/__tests__/operations/entry/filtering/mocks/fields.ts
  packages/api-headless-cms-ddb/__tests__/operations/helpers/pluginsContainer.ts
  packages/api-headless-cms-ddb/src/dynamoDb/storage/richText.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/createExpressions.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/createFields.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/createFilters.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/filter.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/fullTextSearch.ts
  packages/api-headless-cms-ddb/src/operations/entry/filtering/values.ts
  packages/api-headless-cms-ddb/src/operations/entry/index.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlAndQueries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlOrQueries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/storageTransform.test.ts
  packages/api-headless-cms/__tests__/filtering/it.ts
  packages/api-headless-cms/__tests__/filtering/product.conditional.test.ts
  packages/api-headless-cms/__tests__/types.ts
  packages/api-headless-cms/tsconfig.build.json
  packages/api-headless-cms/tsconfig.json
Labels: feature

#2924 fix(api-headless-cms): add missing lifecycle events and parameters
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/crud/contentModelGroup.crud.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#2930 refactor(api-headless-cms): remove unnecessary code and checks
  packages/api-headless-cms/src/crud/contentModel.crud.ts
Labels: feature

#2934 feat(api-headless-cms): dynamic zone converter
  packages/api-headless-cms-ddb-es/src/operations/entry/index.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModelToSDL.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModelToSDL.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/dynamicZoneField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/pageWithDynamicZonesModel.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/page.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/page.read.ts
  packages/api-headless-cms/__tests__/converters/mocks/fieldIdStorageConverter.ts
  packages/api-headless-cms/__tests__/testHelpers/usePageManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/usePageReadHandler.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/fieldConverters/CmsModelDynamicZoneFieldConverterPlugin.ts
  packages/api-headless-cms/src/fieldConverters/index.ts
  packages/api-headless-cms/src/graphqlFields/dynamicZone/dynamicZoneField.ts
  packages/api-headless-cms/src/graphqlFields/object.ts
  packages/api-headless-cms/src/plugins/CmsModelFieldConverterPlugin.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#2936 fix(api-dynamodb-to-elasticsearch): lower p-retry version
  packages/api-dynamodb-to-elasticsearch/package.json
  yarn.lock
Labels: bug

#2943 feat(handler): custom error handling
  apps/api/graphql/tsconfig.json
  packages/handler-aws/src/dynamodb/index.ts
  packages/handler-aws/src/eventBridge/index.ts
  packages/handler-aws/src/gateway/index.ts
  packages/handler-aws/src/raw/index.ts
  packages/handler-aws/src/s3/index.ts
  packages/handler-aws/src/sqs/index.ts
  packages/handler/__tests__/customErrorHandler.test.ts
  packages/handler/__tests__/modifyFastify.test.ts
  packages/handler/src/fastify.ts
  packages/handler/src/index.ts
  packages/handler/src/plugins/ModifyFastifyPlugin.ts
Labels: feature

#2939 feat(handler): ability to override default on request event
  packages/handler/__tests__/onRequest.test.ts
  packages/handler/src/fastify.ts
  packages/handler/src/index.ts
  packages/handler/src/plugins/HandlerOnRequestPlugin.ts
Labels: feature

#2931 refactor(api-mailer): replace joi validation lib with zod
  packages/api-mailer/package.json
  packages/api-mailer/src/crud/settings.crud.ts
  packages/api-mailer/src/crud/settings/validation.ts
  packages/api-mailer/src/crud/transport/onTransportBeforeSend.ts
  packages/api-mailer/src/crud/transporter.crud.ts
  yarn.lock
Labels: feature

#2949 refactor(api-aco): replace joi validation library with zod
  packages/api-aco/package.json
  packages/api-aco/src/context/folders.ts
  packages/api-aco/src/context/links.ts
  packages/api-aco/src/types.ts
  yarn.lock
Labels: feature

#2954 fix(api-headless-cms): handle non-graphql exception on generate schema
  packages/api-headless-cms/src/graphql/graphQLHandlerFactory.ts
Labels: bug

#2956 fix(api-headless-cms): default limit for list entries
  packages/api-apw/__tests__/graphql/commentOnChangeRequest.test.ts
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#2960 fix(api-i18n): variable keeps old tenant after switch between tenants
  packages/api-i18n/src/graphql/crud/index.ts
  packages/api-i18n/src/graphql/crud/locales.crud.ts
  packages/api-i18n/src/graphql/crud/system.crud.ts
Labels: bug

#2959 feat(api-headless-cms): replace commodo in group crud with zod
  packages/api-headless-cms/__tests__/contentAPI/contentModelGroup.crud.test.ts
  packages/api-headless-cms/package.json
  packages/api-headless-cms/src/crud/contentModelGroup.crud.ts
  packages/api-headless-cms/src/crud/contentModelGroup/validation.ts
  packages/error/package.json
  packages/utils/__tests__/createZodError.test.ts
  packages/utils/package.json
  packages/utils/src/createZodError.ts
  packages/utils/src/index.ts
  yarn.lock
Labels: feature

#2962 feat(api-headless-cms): switch to zod validation for models and fields
  package.json
  packages/api-headless-cms/package.json
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/crud/contentModel/createFieldModels.ts
  packages/api-headless-cms/src/crud/contentModel/fieldIdValidation.ts
  packages/api-headless-cms/src/crud/contentModel/idValidation.ts
  packages/api-headless-cms/src/crud/contentModel/models.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/crud/contentModel/validation.ts
  packages/api-headless-cms/src/types.ts
  yarn.lock
Labels: feature

#2967 feat(app-headless-cms): description field
  packages/app-headless-cms/src/admin/components/ContentModelEditor/ContentModelEditorProvider.tsx
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
  packages/app-headless-cms/src/admin/graphql/contentModels.ts
  packages/app-headless-cms/src/types/model.ts
Labels: feature

#2973 feat(api-headless-cms): add image field to model
  packages/api-headless-cms-ddb-es/src/definitions/model.ts
  packages/api-headless-cms-ddb/src/definitions/model.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/contentAPI/pluginsContentModels.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/page.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/__tests__/testHelpers/graphql/contentModel.ts
  packages/api-headless-cms/src/crud/contentModel/fields/descriptionField.ts
  packages/api-headless-cms/src/crud/contentModel/fields/imageField.ts
  packages/api-headless-cms/src/crud/contentModel/fields/titleField.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/crud/contentModel/validation.ts
  packages/api-headless-cms/src/graphql/schema/contentEntries.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
  packages/api-headless-cms/src/graphql/schema/createManageSDL.ts
  packages/api-headless-cms/src/types.ts
  packages/api-headless-cms/src/utils/getEntryImage.ts
Labels: feature

#2975 feat(app-headless-cms): image field
  packages/api-headless-cms/src/crud/contentModel/validation.ts
  packages/api-headless-cms/src/graphql/schema/createManageResolvers.ts
  packages/app-headless-cms/src/admin/components/ContentModelEditor/ContentModelEditorProvider.tsx
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
  packages/app-headless-cms/src/admin/graphql/contentModels.ts
  packages/app-headless-cms/src/types/model.ts
Labels: feature

#2976 feat(app-headless-cms): move field type names to end of field UI
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
Labels: feature

#2977 feat(api-headless-cms): create a new model with default fields
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.defaultFields.test.ts
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/crud/contentModel/defaultFields.ts
  packages/api-headless-cms/src/crud/contentModel/validation.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
Labels: feature

#2972 fix(handler): correct order of reply output
  packages/handler/__tests__/onRequest.test.ts
  packages/handler/src/fastify.ts
Labels: feature

#2970 fix(app-apw): wrong graphql calls
  packages/app-apw/src/index.tsx
  packages/app-apw/src/plugins/cms/ApwOnEntryDelete.tsx
  packages/app-apw/src/plugins/cms/ApwOnEntryPublish.tsx
  packages/app-apw/src/plugins/cms/PublishEntryHocs.tsx
  packages/app-apw/src/plugins/pageBuilder/PublishPageHocs.tsx
  packages/app-headless-cms/src/admin/views/contentEntries/ContentEntry/header/index.tsx
  packages/app-headless-cms/src/admin/views/contentEntries/ContentEntry/header/requestChanges/RequestChanges.tsx
  packages/app-headless-cms/src/admin/views/contentEntries/ContentEntry/header/requestReview/RequestReview.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/header/index.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/header/requestChanges/RequestChanges.tsx
  packages/app-page-builder/src/admin/plugins/pageDetails/header/requestReview/RequestReview.tsx
Labels: bug

#2989 fix(api-headless-cms): search with dash in term
  packages/api-elasticsearch/src/normalize.ts
  packages/api-headless-cms-ddb-es/__tests__/__api__/environment.js
  packages/api-headless-cms/__tests__/contentAPI/search.test.ts
  packages/api-headless-cms/src/context.ts
  packages/api-headless-cms/src/crud/index.ts
  packages/api-headless-cms/src/index.ts
Labels: bug

#2994 fix(app-mailer): reload component on state change
  packages/app-mailer/src/plugins/Module.tsx
Labels: bug
