Repository webiny/webiny-js, pull requests merged in 2023-03, with the labels that each got.

#3069 fix(app-page-builder-elements): exclude page only if Page context exists
  packages/app-page-builder-elements/src/hooks/usePage.ts
  packages/app-page-builder-elements/src/renderers/pagesList/index.tsx
Labels: bug

#3091 fix(serverless-cms-aws): execute apw schedule action handler
  packages/api-apw/src/scheduler/handlers/executeAction/index.ts
  packages/api-apw/src/scheduler/handlers/scheduleAction/scheduleAction.utils.ts
  packages/serverless-cms-aws/handlers/ddb-es/api/apw/executeAction/src/index.ts
  packages/serverless-cms-aws/handlers/ddb-es/core/dynamoToElastic/src/index.ts
  packages/serverless-cms-aws/handlers/ddb/api/apw/executeAction/src/index.ts
Labels: bug

#3110 feat(app-headless-cms): singular and plural model api name
  cypress/integration/admin/headlessCms/contentModel/contentModels.spec.js
  packages/api-headless-cms/__tests__/contentAPI/contentEntry.withId.test.ts
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/crud/contentModel/validation.ts
  packages/api-headless-cms/src/graphql/schema/schemaPlugins.ts
  packages/api-headless-cms/src/utils/removeNullValues.ts
  packages/app-headless-cms/src/admin/components/FieldEditor/Field.tsx
  packages/app-headless-cms/src/admin/graphql/contentModels.ts
  packages/app-headless-cms/src/admin/hooks/index.ts
  packages/app-headless-cms/src/admin/hooks/useContentModels.ts
  packages/app-headless-cms/src/admin/plugins/editor/formSettings/components/GeneralSettings.tsx
  packages/app-headless-cms/src/admin/views/contentModels/CloneContentModelDialog.tsx
  packages/app-headless-cms/src/admin/views/contentModels/ContentModels.tsx
  packages/app-headless-cms/src/admin/views/contentModels/ContentModelsDataList.tsx
  packages/app-headless-cms/src/admin/views/contentModels/NewContentModelDialog.tsx
  packages/app-headless-cms/src/admin/views/contentModels/helpers/apiNameValidator.ts
  packages/app-headless-cms/src/admin/views/contentModels/helpers/nameValidator.ts
  packages/app-headless-cms/src/admin/viewsGraphql.ts
  packages/app-headless-cms/src/types/model.ts
Labels: cms

#3031 feat: add other as an option to specific fields
  apps/theme/layouts/forms/DefaultFormLayout/fields/Checkbox.tsx
  apps/theme/layouts/forms/DefaultFormLayout/fields/Input.tsx
  apps/theme/layouts/forms/DefaultFormLayout/fields/Radio.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFields/checkboxes.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFields/components/OptionsList.tsx
  packages/app-form-builder/src/admin/plugins/editor/formFields/radioButtons.tsx
  packages/app-form-builder/src/components/Form/FormRender.tsx
  packages/app-page-builder-elements/src/renderers/form/FormRender.tsx
  packages/app-page-builder-elements/src/renderers/form/FormRender/functions/createFormSubmission.ts
  packages/cwp-template-aws/template/common/apps/theme/layouts/forms/DefaultFormLayout/fields/Checkbox.tsx
  packages/cwp-template-aws/template/common/apps/theme/layouts/forms/DefaultFormLayout/fields/Input.tsx
  packages/cwp-template-aws/template/common/apps/theme/layouts/forms/DefaultFormLayout/fields/Radio.tsx
Labels: migration

#3116 test(api-headless-cms): singular and plural model name
  cypress/integration/admin/headlessCms/contentEntry/contentEntries.spec.js
  cypress/integration/admin/headlessCms/contentEntry/searchSortAndFilterEntries.spec.js
  cypress/support/commands.js
  cypress/support/headlessCms/cmsListBooks.js
  cypress/support/headlessCms/graphql.js
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModelToSDL.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModelToSDL.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/dynamicZoneField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/fieldValidations.test.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.noValidation.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/pageWithDynamicZonesModel.ts
  packages/api-headless-cms/__tests__/contentAPI/pluginsContentModels.test.ts
  packages/api-headless-cms/__tests__/contentAPI/pluginsContentModelsRef.test.ts
  packages/api-headless-cms/__tests__/contentAPI/refField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.read.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/page.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/page.read.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.read.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.read.ts
  packages/api-headless-cms/__tests__/testHelpers/useArticleManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useArticleReadHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useAuthorManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useBugManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useCategoryManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useCategoryReadHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useFruitManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useFruitReadHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/usePageManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/usePageReadHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useProductManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useProductReadHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useReviewManageHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useReviewReadHandler.ts
  packages/api-headless-cms/src/crud/contentModel/beforeCreate.ts
  packages/api-headless-cms/src/crud/contentModel/beforeUpdate.ts
  packages/api-headless-cms/src/crud/contentModel/validateModel.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/graphql/schema/createManageSDL.ts
  packages/api-headless-cms/src/graphql/schema/createReadSDL.ts
  packages/api-headless-cms/src/graphql/schema/schemaPlugins.ts
  packages/api-headless-cms/src/graphqlFields/dynamicZone/dynamicZoneField.ts
  packages/api-headless-cms/src/graphqlFields/object.ts
  packages/api-headless-cms/src/graphqlFields/ref.ts
  packages/api-headless-cms/src/types.ts
  packages/api-headless-cms/src/utils/createTypeFromFields.ts
  packages/api-headless-cms/src/utils/renderFields.ts
  packages/api-headless-cms/src/utils/renderInputFields.ts
  packages/app-headless-cms/src/admin/graphql/contentEntries.ts
  packages/app-headless-cms/src/admin/plugins/fields/dynamicZone.tsx
Labels: feature

#3117 feat(migrations): model singular and plural
  packages/migrations/__tests__/migrations/5.35.0/005/005.data.ts
  packages/migrations/__tests__/migrations/5.35.0/005/005.test.ts
  packages/migrations/__tests__/utils/insertTestData.ts
  packages/migrations/package.json
  packages/migrations/src/ddb-es.ts
  packages/migrations/src/ddb.ts
  packages/migrations/src/migrations/5.35.0/001/FileSettingsMigration.ts
  packages/migrations/src/migrations/5.35.0/001/createFileEntity.ts
  packages/migrations/src/migrations/5.35.0/001/createSettingsEntity.ts
  packages/migrations/src/migrations/5.35.0/002/createSettingsEntity.ts
  packages/migrations/src/migrations/5.35.0/002/index.ts
  packages/migrations/src/migrations/5.35.0/003/createUserEntity.ts
  packages/migrations/src/migrations/5.35.0/004/createTenantEntity.ts
  packages/migrations/src/migrations/5.35.0/005/createLocaleEntity.ts
  packages/migrations/src/migrations/5.35.0/005/createLocalePartitionKey.ts
  packages/migrations/src/migrations/5.35.0/005/createModelEntity.ts
  packages/migrations/src/migrations/5.35.0/005/createModelPartitionKey.ts
  packages/migrations/src/migrations/5.35.0/005/createTenantEntity.ts
  packages/migrations/src/migrations/5.35.0/005/index.ts
  packages/migrations/src/migrations/5.35.0/005/types.ts
  yarn.lock
Labels: feature

#3121 feat: improve folders and search records listing
  packages/app-aco/src/contexts/records.tsx
  packages/app-aco/src/hooks/index.ts
  packages/app-aco/src/hooks/useAcoList.ts
  packages/app-aco/src/hooks/useRecords.ts
  packages/app-aco/src/index.ts
  packages/app-aco/src/sorting.tsx
  packages/app-aco/src/types.ts
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
Labels: page-builder

#3127 fix: data migrations execution error log
  packages/data-migration/package.json
  packages/data-migration/src/MigrationRunner.ts
  packages/data-migration/src/types.ts
  packages/data-migration/tsconfig.build.json
  packages/data-migration/tsconfig.json
  packages/migrations/__tests__/migrations/5.35.0/005/005.test.ts
  packages/serverless-cms-aws/src/api/plugins/executeDataMigrations.ts
  yarn.lock
Labels: bug

#3129 fix(cypress): missing plural and singular model api name
  cypress/integration/admin/headlessCms/contentModel/contentModels.spec.js
  cypress/integration/admin/headlessCms/contentModel/searchSortModels.spec.js
Labels: bug

#3012 feat: grid and cell adjustments
  apps/admin/src/plugins/pageBuilder/editorPlugins.ts
  packages/app-page-builder-elements/src/modifiers/styles/grid.ts
  packages/app-page-builder-elements/src/modifiers/styles/gridFlexWrap.ts
  packages/app-page-builder-elements/src/modifiers/styles/verticalAlign.ts
  packages/app-page-builder/src/contexts/PageBuilder/PageElementsProvider.tsx
  packages/app-page-builder/src/editor/contexts/EditorPageElementsProvider.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/cell/VerticalAlignSettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/cell/index.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/grid/CounterInput.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/grid/GridSettings.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/grid/GridSize.tsx
  packages/app-page-builder/src/editor/plugins/elementSettings/index.ts
  packages/app-page-builder/src/editor/plugins/elements/block/PeBlock.tsx
  packages/app-page-builder/src/editor/plugins/elements/cell/PeCell.tsx
  packages/app-page-builder/src/editor/plugins/elements/cell/index.tsx
  packages/app-page-builder/src/editor/plugins/elements/grid/index.tsx
  packages/app-page-builder/src/types.ts
  packages/cwp-template-aws/template/common/apps/admin/src/plugins/pageBuilder/editorPlugins.ts
Labels: migration

#3095 Introduce Application Name-based Environment Variables Naming
  packages/project-utils/bundling/app/config/env.js
  packages/project-utils/bundling/app/config/webpack.config.js
  packages/pulumi-aws/src/utils/lambdaEnvVariables.ts
Labels: changelog

#3126 Introduce New Frontend Utility Functions (`getLocaleCode`, `getTenantId`, `getApiUrl`, ...)
  packages/app-website/src/index.tsx
  packages/app-website/src/utils/getPrerenderId.ts
  packages/app-website/src/utils/index.ts
  packages/app/src/plugins/LocaleHeaderLinkPlugin.ts
  packages/app/src/plugins/TenantHeaderLinkPlugin.ts
  packages/app/src/utils/getApiUrl.ts
  packages/app/src/utils/getGqlApiUrl.ts
  packages/app/src/utils/getHeadlessCmsGqlApiUrl.ts
  packages/app/src/utils/getLocaleCode.ts
  packages/app/src/utils/getPrerenderId.ts
  packages/app/src/utils/getTenantId.ts
  packages/app/src/utils/index.ts
  packages/app/src/utils/isLocalhost.ts
  packages/app/src/utils/isPrerendering.ts
Labels: changelog

#3155 Page Builder Pages - Use SEO Title Instead Of General Settings Title
  packages/app-page-builder/src/editor/plugins/pageSettings/index.tsx
  packages/app-page-builder/src/editor/ui/views/GeneralSettingsView.ts
  packages/app-website/src/Page/PageRenderer.tsx
Labels: changelog

#3152 Page Builder Editor - Ensure Active Element's Borders Are Always Visible
  packages/app-page-builder-elements/src/components/Elements.tsx
  packages/app-page-builder/src/editor/contexts/EditorPageElementsProvider/ElementControlsOverlay.tsx
  packages/app-page-builder/src/editor/contexts/EditorPageElementsProvider/ElementControlsOverlay/ElementControlsOverlayBorders.tsx
Labels: changelog

#3153 Page Builder - Ensure No Trailing Slashes Are Present In Page Path
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
Labels: changelog
