Repository webiny/webiny-js, pull requests merged in 2023-02, with the labels that each got.

#2961 feat: add import/export capabilities to page datatable
  apps/api/graphql/src/index.ts
  apps/api/pageBuilder/import/process/package.json
  apps/api/pageBuilder/import/process/src/index.ts
  apps/api/pageBuilder/import/process/tsconfig.json
  packages/api-aco/package.json
  packages/api-aco/src/index.ts
  packages/api-aco/src/subscriptions/aftePageCreate.ts
  packages/api-aco/src/subscriptions/index.ts
  packages/api-aco/src/types.ts
  packages/api-aco/tsconfig.build.json
  packages/api-aco/tsconfig.json
  packages/api-page-builder-import-export/src/graphql/crud/pages.crud.ts
  packages/api-page-builder-import-export/src/graphql/graphql/pages.gql.ts
  packages/api-page-builder-import-export/src/graphql/types.ts
  packages/api-page-builder-import-export/src/import/create/index.ts
  packages/api-page-builder-import-export/src/import/create/pagesHandler.ts
  packages/api-page-builder-import-export/src/import/process/index.ts
  packages/api-page-builder-import-export/src/import/process/pagesHandler.ts
  packages/api-page-builder/package.json
  packages/api-page-builder/src/graphql/crud/pages.crud.ts
  packages/api-page-builder/src/graphql/graphql/pages.gql.ts
  packages/api-page-builder/src/graphql/index.ts
  packages/api-page-builder/src/graphql/subscriptions/afterSystemInstall.ts
  packages/api-page-builder/src/graphql/subscriptions/index.ts
  packages/api-page-builder/src/graphql/types.ts
  packages/api-page-builder/tsconfig.build.json
  packages/api-page-builder/tsconfig.json
  packages/app-page-builder/src/admin/components/Table/Header/ButtonsCreate/ButtonsCreate.tsx
  packages/app-page-builder/src/admin/components/Table/Header/ButtonsCreate/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/ButtonsCreate/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Header/Header.tsx
  packages/app-page-builder/src/admin/components/Table/Header/TableActions/TableActions.tsx
  packages/app-page-builder/src/admin/components/Table/Header/TableActions/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/TableActions/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Header/Title/Title.tsx
  packages/app-page-builder/src/admin/components/Table/Header/Title/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/Title/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Header/index.tsx
  packages/app-page-builder/src/admin/components/Table/Header/styled.tsx
  packages/app-page-builder/src/admin/components/Table/Table/index.tsx
  packages/app-page-builder/src/admin/graphql/pageImportExport.gql.ts
  packages/app-page-builder/src/admin/graphql/pages.ts
  packages/app-page-builder/src/admin/views/Pages/Table/Main.tsx
  packages/app-page-builder/src/admin/views/Pages/Table/styled.tsx
  packages/app-page-builder/src/admin/views/Pages/hooks/useCreatePage.ts
  packages/app-page-builder/src/admin/views/Pages/hooks/useImportPage.ts
  packages/app-page-builder/src/editor/plugins/defaultBar/components/ExportPageButton/useExportPageDialog.tsx
  packages/ui/src/DataTable/DataTable.tsx
  yarn.lock
Labels: page-builder

#3001 test(api-headless-cms): remove unnecessary until
  packages/api-aco/package.json
  packages/api-headless-cms-ddb-es/__tests__/__api__/environment.js
  packages/api-headless-cms/__tests__/contentAPI/cmsEntryStatus.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntryHooks.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntryMetaField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/contentAPI/deepNestedObject.test.ts
  packages/api-headless-cms/__tests__/contentAPI/dynamicZoneField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/entryPaginatipon.test.ts
  packages/api-headless-cms/__tests__/contentAPI/fieldValidations.test.ts
  packages/api-headless-cms/__tests__/contentAPI/filtering.test.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlAndQueries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/graphQlOrQueries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/latestEntries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/lockedFields.test.ts
  packages/api-headless-cms/__tests__/contentAPI/model.delete.test.ts
  packages/api-headless-cms/__tests__/contentAPI/pluginsContentModels.test.ts
  packages/api-headless-cms/__tests__/contentAPI/refField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/references.test.ts
  packages/api-headless-cms/__tests__/contentAPI/republish.entries.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.apiKey.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.apiKey.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/richTextField.test.ts
  packages/api-headless-cms/__tests__/contentAPI/sorting.test.ts
  packages/api-headless-cms/__tests__/contentAPI/storageTransform.test.ts
  packages/api-headless-cms/__tests__/filtering/product/category.ts
  packages/api-headless-cms/__tests__/filtering/product/entries.ts
  packages/api-headless-cms/__tests__/graphql/numbersModel.test.ts
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/types.ts
Labels: feature

#3006 fix(api-headless-cms): graphql group slug
  packages/api-headless-cms/__tests__/contentAPI/contentModel.clone.test.ts
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/__tests__/contentAPI/pluginsContentModels.test.ts
  packages/api-headless-cms/__tests__/testHelpers/graphql/contentModel.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
  packages/handler/src/Context.ts
  packages/handler/src/fastify.ts
  packages/handler/src/types.ts
Labels: bug

#3011 fix(api-headless-cms): field validation
  packages/api-headless-cms/__tests__/contentAPI/contentModelToSDL.read.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/cmsContentPermissions.ts
  packages/api-headless-cms/__tests__/helpers/filterModelFields.test.ts
  packages/api-headless-cms/__tests__/helpers/renderSortEnum.test.ts
  packages/api-headless-cms/__tests__/testHelpers/plugins.ts
  packages/api-headless-cms/__tests__/testHelpers/useGraphQLHandler.ts
  packages/api-headless-cms/__tests__/testHelpers/useHandler.ts
  packages/api-headless-cms/__tests__/validations/fields/number.ts
  packages/api-headless-cms/__tests__/validations/fields/object.ts
  packages/api-headless-cms/__tests__/validations/fields/text.ts
  packages/api-headless-cms/__tests__/validations/fields/types.ts
  packages/api-headless-cms/__tests__/validations/models/test.ts
  packages/api-headless-cms/__tests__/validations/validateModelFields.test.ts
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/crud/contentModel/beforeCreate.ts
  packages/api-headless-cms/src/crud/contentModel/beforeUpdate.ts
  packages/api-headless-cms/src/crud/contentModel/validateModel.ts
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/graphql/buildSchemaPlugins.ts
  packages/api-headless-cms/src/graphql/createExecutableSchema.ts
  packages/api-headless-cms/src/graphql/generateSchema.ts
  packages/api-headless-cms/src/graphql/graphQLHandlerFactory.ts
  packages/api-headless-cms/src/graphql/index.ts
  packages/api-headless-cms/src/graphql/schema/baseContentSchema.ts
  packages/api-headless-cms/src/graphql/schema/baseSchema.ts
  packages/api-headless-cms/src/graphql/schema/contentEntries.ts
  packages/api-headless-cms/src/graphql/schema/contentModelGroups.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
  packages/api-headless-cms/src/graphql/schema/schemaPlugins.ts
  packages/api-headless-cms/src/utils/filterModelFields.ts
Labels: bug

#3018 fix(api-headless-cms): nested file graphql
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.images.test.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModelGroup.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.noValidation.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/models/images.ts
  packages/api-headless-cms/__tests__/types.ts
  packages/api-headless-cms/src/graphqlFields/object.ts
Labels: bug

#3021 fix(api-headless-cms): no error response on exception
  packages/api-headless-cms/src/graphql/schema/contentEntries.ts
Labels: bug

#3019 fix(api-headless-cms): allow custom entry id
  packages/api-headless-cms/__tests__/contentAPI/contentEntry.withId.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/category.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/page.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/review.manage.ts
  packages/api-headless-cms/src/crud/contentEntry.crud.ts
  packages/api-headless-cms/src/graphql/schema/createManageSDL.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#3024 fix(api-headless-cms): model description validation
  packages/api-headless-cms/__tests__/contentAPI/contentModel.crud.test.ts
  packages/api-headless-cms/src/crud/contentModel.crud.ts
  packages/api-headless-cms/src/crud/contentModel/validation.ts
  packages/api-headless-cms/src/types.ts
Labels: bug

#3025 fix(api-headless-cms): full text search
  packages/api-elasticsearch/__tests__/normalize.ts
  packages/api-elasticsearch/__tests__/search/japanese.test.ts
  packages/api-elasticsearch/src/normalize.ts
  packages/api-elasticsearch/src/plugins/operator/contains.ts
  packages/api-elasticsearch/src/plugins/operator/japanese/contains.ts
  packages/api-elasticsearch/src/plugins/operator/notContains.ts
  packages/api-file-manager-ddb-es/src/operations/files/body.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/contains.test.ts
  packages/api-headless-cms-ddb-es/__tests__/filtering/not_contains.test.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/body.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/fullTextSearch.ts
  packages/api-headless-cms-ddb-es/src/operations/entry/elasticsearch/fullTextSearchFields.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchFullTextSearchPlugin.ts
  packages/api-headless-cms-ddb-es/src/plugins/index.ts
  packages/api-headless-cms/__tests__/contentAPI/contentEntries.test.ts
Labels: bug

#3033 fix(api-apw): content review status when non mandatory steps
  packages/api-apw/src/plugins/hooks/initializeContentReviewSteps.ts
Labels: bug

#3035 fix(api-apw): scheduling pages to be published
  packages/api-apw/src/scheduler/handlers/executeAction/index.ts
  packages/api-apw/src/scheduler/handlers/executeAction/plugins/ApplicationGraphQL.ts
  packages/api-apw/src/scheduler/handlers/executeAction/plugins/HeadlessCMSGraphQL.ts
  packages/api-apw/src/scheduler/handlers/executeAction/plugins/PageBuilderGraphQL.ts
Labels: bug

#3037 fix(api-headless-cms): mark locked fields error
  packages/api-headless-cms/src/crud/contentEntry/markLockedFields.ts
Labels: bug

#3036 fix(api-apw): wrong arn in the cms plugin
  packages/api-apw/src/scheduler/handlers/executeAction/plugins/HeadlessCMSGraphQL.ts
  packages/api-apw/src/scheduler/handlers/utils.ts
Labels: bug

#3045 fix: lock babel types package version
  packages/project-utils/packages/createBabelConfigForNode.js
  yarn.lock
Labels: bug

#3048 fix(api-headles-cms): model graphql validation
  packages/api-headless-cms/src/crud/contentModel/validateModelFields.ts
  packages/api-headless-cms/src/graphql/schema/baseContentSchema.ts
  packages/api-headless-cms/src/graphql/schema/contentEntries.ts
  packages/api-headless-cms/src/graphql/schema/contentModelGroups.ts
  packages/api-headless-cms/src/graphql/schema/contentModels.ts
Labels: bug

#3051 fix(api-headless-cms-ddb-es): plugin loading on storage ops init
  packages/api-headless-cms-ddb-es/src/dynamoDb/storage/richText.ts
  packages/api-headless-cms-ddb-es/src/elasticsearch/indexing/defaultFieldIndexing.ts
  packages/api-headless-cms-ddb-es/src/index.ts
  packages/api-headless-cms-ddb-es/src/plugins/CmsEntryElasticsearchQueryBuilderValueSearchPlugin.ts
  packages/api-headless-cms/__tests__/contentAPI/mocks/contentModels.ts
  packages/api-headless-cms/__tests__/contentAPI/resolvers.manage.test.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.manage.ts
  packages/api-headless-cms/__tests__/contentAPI/snapshots/product.read.ts
  packages/api-headless-cms/__tests__/contentAPI/storageTransform.test.ts
  packages/api-headless-cms/__tests__/testHelpers/useProductManageHandler.ts
  packages/api-headless-cms/__tests__/types.ts
Labels: bug

#3059 Support for legacy content in PB block editor form
  packages/lexical-editor-pb-element/src/plugins/elementSettings/variables/RichVariableInputPlugin.tsx
  packages/lexical-editor-pb-element/src/plugins/elementSettings/variables/TextVariableInputPlugin.tsx
Labels: page-builder
